services {
  name: "logz"
  grpc_server {
    address{
      host: "0.0.0.0"
      port: 4001
    }
    enable_gzip: false
    exponential_backoff {
      override_max_delay {
        seconds: 1
      }
    }
  }
  update_frequency {
    milliseconds: 5000
  }
  timeout {
    seconds: 10
  }
}
services {
  name: "expz"
  grpc_server {
    address{
      host: "0.0.0.0"
      port: 4002
    }
    enable_gzip: false
    exponential_backoff {
      override_max_delay {
        seconds: 1
      }
    }
  }
  update_frequency {
    milliseconds: 5000
  }
  timeout {
    seconds: 10
  }
}
services {
  name: "addz"
  grpc_server {
    address{
      host: "0.0.0.0"
      port: 4003
    }
    enable_gzip: false
    exponential_backoff {
      override_max_delay {
        seconds: 1
      }
    }
  }
  update_frequency {
    milliseconds: 5000
  }
  timeout {
    seconds: 10
  }
}
services {
  name: "userz"
  grpc_server {
    address{
      host: "0.0.0.0"
      port: 4004
    }
    enable_gzip: false
    exponential_backoff {
      override_max_delay {
        seconds: 1
      }
    }
  }
  update_frequency {
    milliseconds: 5000
  }
  timeout {
    seconds: 10
  }
}