services {
  name: "logz"
  address {
    host: "0.0.0.0"
    port: 4001
  }
  update_frequency {
    seconds: 3
  }
  timeout {
    seconds: 10
  }
}
services {
  name: "expz"
  address {
    host: "0.0.0.0"
    port: 4002
  }
  update_frequency {
    seconds: 3
  }
  timeout {
    seconds: 10
  }
}
services {
  name: "addz"
  address {
    host: "0.0.0.0"
    port: 4003
  }
  update_frequency {
    milliseconds: 3000
  }
  timeout {
    seconds: 10
  }
}