bind_address {
  host: "0.0.0.0"
  port: 4003
}
json_bind_address {
 host: "0.0.0.0"
 port: 7003
}
logz_server{
  address {
    host: "0.0.0.0"
    port: 4001
  }
}
expz_server {
  address {
    host: "0.0.0.0"
    port: 4002
  }
}
userz_server {
  address {
    host: "0.0.0.0"
    port: 4004
  }
}