// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logz/logz.proto

package logz

import (
	fmt "fmt"
	proto1 "github.com/explodes/serving/proto"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Level int32

const (
	Level_UNKNOWN Level = 0
	Level_DEBUG   Level = 1
	Level_INFO    Level = 2
	Level_WARN    Level = 3
	Level_ERROR   Level = 4
)

var Level_name = map[int32]string{
	0: "UNKNOWN",
	1: "DEBUG",
	2: "INFO",
	3: "WARN",
	4: "ERROR",
}

var Level_value = map[string]int32{
	"UNKNOWN": 0,
	"DEBUG":   1,
	"INFO":    2,
	"WARN":    3,
	"ERROR":   4,
}

func (x Level) String() string {
	return proto.EnumName(Level_name, int32(x))
}

func (Level) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_623f03371c6d65cf, []int{0}
}

type Entry struct {
	// When the entry occurred.
	Timestamp *proto1.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Optional time when the entry ended.
	EndTimestamp *proto1.Timestamp `protobuf:"bytes,2,opt,name=end_timestamp,json=endTimestamp,proto3" json:"end_timestamp,omitempty"`
	// Level of the log.
	Level Level `protobuf:"varint,3,opt,name=level,proto3,enum=logz.Level" json:"level,omitempty"`
	// Log message.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Any additional information to record.
	Ext                  *any.Any `protobuf:"bytes,5,opt,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}
func (*Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_623f03371c6d65cf, []int{0}
}

func (m *Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Entry.Unmarshal(m, b)
}
func (m *Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Entry.Marshal(b, m, deterministic)
}
func (m *Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Entry.Merge(m, src)
}
func (m *Entry) XXX_Size() int {
	return xxx_messageInfo_Entry.Size(m)
}
func (m *Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Entry proto.InternalMessageInfo

func (m *Entry) GetTimestamp() *proto1.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Entry) GetEndTimestamp() *proto1.Timestamp {
	if m != nil {
		return m.EndTimestamp
	}
	return nil
}

func (m *Entry) GetLevel() Level {
	if m != nil {
		return m.Level
	}
	return Level_UNKNOWN
}

func (m *Entry) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Entry) GetExt() *any.Any {
	if m != nil {
		return m.Ext
	}
	return nil
}

type Frame struct {
	// ID of and end-to-end series of RPCs.
	StackId string `protobuf:"bytes,1,opt,name=stack_id,json=stackId,proto3" json:"stack_id,omitempty"`
	// ID of an individual RPC.
	OperationId string `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// Name of an individual RPC.
	OperationName string `protobuf:"bytes,3,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	// Parent operation ID of an individual RPC.
	ParentOperationId    string   `protobuf:"bytes,4,opt,name=parent_operation_id,json=parentOperationId,proto3" json:"parent_operation_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Frame) Reset()         { *m = Frame{} }
func (m *Frame) String() string { return proto.CompactTextString(m) }
func (*Frame) ProtoMessage()    {}
func (*Frame) Descriptor() ([]byte, []int) {
	return fileDescriptor_623f03371c6d65cf, []int{1}
}

func (m *Frame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Frame.Unmarshal(m, b)
}
func (m *Frame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Frame.Marshal(b, m, deterministic)
}
func (m *Frame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Frame.Merge(m, src)
}
func (m *Frame) XXX_Size() int {
	return xxx_messageInfo_Frame.Size(m)
}
func (m *Frame) XXX_DiscardUnknown() {
	xxx_messageInfo_Frame.DiscardUnknown(m)
}

var xxx_messageInfo_Frame proto.InternalMessageInfo

func (m *Frame) GetStackId() string {
	if m != nil {
		return m.StackId
	}
	return ""
}

func (m *Frame) GetOperationId() string {
	if m != nil {
		return m.OperationId
	}
	return ""
}

func (m *Frame) GetOperationName() string {
	if m != nil {
		return m.OperationName
	}
	return ""
}

func (m *Frame) GetParentOperationId() string {
	if m != nil {
		return m.ParentOperationId
	}
	return ""
}

func init() {
	proto.RegisterEnum("logz.Level", Level_name, Level_value)
	proto.RegisterType((*Entry)(nil), "logz.Entry")
	proto.RegisterType((*Frame)(nil), "logz.Frame")
}

func init() { proto.RegisterFile("logz/logz.proto", fileDescriptor_623f03371c6d65cf) }

var fileDescriptor_623f03371c6d65cf = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4f, 0x6b, 0xd4, 0x40,
	0x14, 0x37, 0xbb, 0x89, 0xdb, 0xbc, 0xb4, 0x35, 0x8e, 0x1e, 0x62, 0x4f, 0xe9, 0x42, 0x65, 0xf1,
	0x30, 0x91, 0x7a, 0xf0, 0x26, 0xb4, 0xb8, 0x95, 0x45, 0x49, 0x60, 0xb0, 0x14, 0xbc, 0x84, 0xd9,
	0xe6, 0x99, 0x0d, 0x26, 0x33, 0x61, 0x32, 0xbb, 0x6c, 0xfc, 0x2c, 0x7e, 0x2f, 0xbf, 0x8e, 0xcc,
	0xc4, 0xdd, 0xe0, 0xc1, 0x4b, 0x98, 0xdf, 0x9f, 0xf7, 0xe7, 0xf7, 0x08, 0x3c, 0xab, 0x65, 0xf9,
	0x33, 0x31, 0x1f, 0xda, 0x2a, 0xa9, 0x25, 0x71, 0xcd, 0xfb, 0x22, 0xb4, 0x20, 0xd1, 0x55, 0x83,
	0x03, 0x7f, 0x71, 0xa5, 0x37, 0x95, 0x2a, 0xf2, 0x96, 0x2b, 0xdd, 0x27, 0xa5, 0x94, 0x65, 0x8d,
	0x89, 0x55, 0xd6, 0xdb, 0xef, 0x09, 0x17, 0xfd, 0x60, 0x9b, 0xff, 0x76, 0xc0, 0x5b, 0x0a, 0xad,
	0x7a, 0xf2, 0x16, 0x7c, 0x53, 0xde, 0x69, 0xde, 0xb4, 0x91, 0x13, 0x3b, 0x8b, 0xe0, 0x9a, 0xd0,
	0x0e, 0xd5, 0xae, 0x12, 0x25, 0xfd, 0x7a, 0x50, 0xd8, 0x68, 0x22, 0xef, 0xe1, 0x0c, 0x45, 0x91,
	0x8f, 0x55, 0x93, 0xff, 0x56, 0x9d, 0xa2, 0x28, 0x8e, 0x88, 0x5c, 0x82, 0x57, 0xe3, 0x0e, 0xeb,
	0x68, 0x1a, 0x3b, 0x8b, 0xf3, 0xeb, 0x80, 0xda, 0x3c, 0x5f, 0x0c, 0xc5, 0x06, 0x85, 0x44, 0x30,
	0x6b, 0xb0, 0xeb, 0x78, 0x89, 0x91, 0x1b, 0x3b, 0x0b, 0x9f, 0x1d, 0x20, 0x79, 0x0d, 0x53, 0xdc,
	0xeb, 0xc8, 0xb3, 0xb3, 0x5e, 0xd2, 0x21, 0x1a, 0x3d, 0x44, 0xa3, 0x37, 0xa2, 0x67, 0xc6, 0x30,
	0xff, 0xe5, 0x80, 0x77, 0xa7, 0x78, 0x83, 0xe4, 0x15, 0x9c, 0x74, 0x9a, 0x3f, 0xfe, 0xc8, 0xab,
	0xc2, 0x06, 0xf3, 0xd9, 0xcc, 0xe2, 0x55, 0x41, 0x2e, 0xe1, 0x54, 0xb6, 0xa8, 0xb8, 0xae, 0xa4,
	0x30, 0xf2, 0xc4, 0xca, 0xc1, 0x91, 0x5b, 0x15, 0xe4, 0x0a, 0xce, 0x47, 0x8b, 0xe0, 0x0d, 0xda,
	0xad, 0x7d, 0x76, 0x76, 0x64, 0x53, 0x33, 0x84, 0xc2, 0x8b, 0x96, 0x2b, 0x14, 0x3a, 0xff, 0xa7,
	0xe1, 0xb0, 0xfc, 0xf3, 0x41, 0xca, 0xc6, 0xb6, 0x6f, 0x3e, 0x80, 0x67, 0x03, 0x93, 0x00, 0x66,
	0xf7, 0xe9, 0xe7, 0x34, 0x7b, 0x48, 0xc3, 0x27, 0xc4, 0x07, 0xef, 0xe3, 0xf2, 0xf6, 0xfe, 0x53,
	0xe8, 0x90, 0x13, 0x70, 0x57, 0xe9, 0x5d, 0x16, 0x4e, 0xcc, 0xeb, 0xe1, 0x86, 0xa5, 0xe1, 0xd4,
	0xc8, 0x4b, 0xc6, 0x32, 0x16, 0xba, 0xb7, 0xf3, 0x6f, 0x71, 0x59, 0xe9, 0xcd, 0x76, 0x4d, 0x1f,
	0x65, 0x93, 0xe0, 0xbe, 0xad, 0x65, 0x81, 0x5d, 0xf2, 0xf7, 0xf4, 0xf6, 0x0f, 0x59, 0x3f, 0xb5,
	0x57, 0x79, 0xf7, 0x27, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x96, 0xf2, 0x73, 0x35, 0x02, 0x00, 0x00,
}
