// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logz/service.proto

package logz

import (
	fmt "fmt"
	proto1 "github.com/explodes/serving/proto"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceConfig struct {
	BindAddress          *proto1.Address `protobuf:"bytes,1,opt,name=bind_address,json=bindAddress,proto3" json:"bind_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ServiceConfig) Reset()         { *m = ServiceConfig{} }
func (m *ServiceConfig) String() string { return proto.CompactTextString(m) }
func (*ServiceConfig) ProtoMessage()    {}
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef5d4fdd9f1c360, []int{0}
}

func (m *ServiceConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceConfig.Unmarshal(m, b)
}
func (m *ServiceConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceConfig.Marshal(b, m, deterministic)
}
func (m *ServiceConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceConfig.Merge(m, src)
}
func (m *ServiceConfig) XXX_Size() int {
	return xxx_messageInfo_ServiceConfig.Size(m)
}
func (m *ServiceConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceConfig proto.InternalMessageInfo

func (m *ServiceConfig) GetBindAddress() *proto1.Address {
	if m != nil {
		return m.BindAddress
	}
	return nil
}

type RecordRequest struct {
	Cookie               string   `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"`
	Stack                *Frame   `protobuf:"bytes,2,opt,name=stack,proto3" json:"stack,omitempty"`
	Entries              []*Entry `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordRequest) Reset()         { *m = RecordRequest{} }
func (m *RecordRequest) String() string { return proto.CompactTextString(m) }
func (*RecordRequest) ProtoMessage()    {}
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef5d4fdd9f1c360, []int{1}
}

func (m *RecordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordRequest.Unmarshal(m, b)
}
func (m *RecordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordRequest.Marshal(b, m, deterministic)
}
func (m *RecordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordRequest.Merge(m, src)
}
func (m *RecordRequest) XXX_Size() int {
	return xxx_messageInfo_RecordRequest.Size(m)
}
func (m *RecordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecordRequest proto.InternalMessageInfo

func (m *RecordRequest) GetCookie() string {
	if m != nil {
		return m.Cookie
	}
	return ""
}

func (m *RecordRequest) GetStack() *Frame {
	if m != nil {
		return m.Stack
	}
	return nil
}

func (m *RecordRequest) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type RecordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordResponse) Reset()         { *m = RecordResponse{} }
func (m *RecordResponse) String() string { return proto.CompactTextString(m) }
func (*RecordResponse) ProtoMessage()    {}
func (*RecordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bef5d4fdd9f1c360, []int{2}
}

func (m *RecordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordResponse.Unmarshal(m, b)
}
func (m *RecordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordResponse.Marshal(b, m, deterministic)
}
func (m *RecordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordResponse.Merge(m, src)
}
func (m *RecordResponse) XXX_Size() int {
	return xxx_messageInfo_RecordResponse.Size(m)
}
func (m *RecordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecordResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ServiceConfig)(nil), "logz.ServiceConfig")
	proto.RegisterType((*RecordRequest)(nil), "logz.RecordRequest")
	proto.RegisterType((*RecordResponse)(nil), "logz.RecordResponse")
}

func init() { proto.RegisterFile("logz/service.proto", fileDescriptor_bef5d4fdd9f1c360) }

var fileDescriptor_bef5d4fdd9f1c360 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0x29, 0x85, 0x20, 0x1c, 0x4a, 0x2b, 0x87, 0x21, 0x64, 0x0a, 0x91, 0x90, 0x90, 0x90,
	0x12, 0xa9, 0x15, 0x0f, 0x40, 0x5b, 0x98, 0x98, 0xcc, 0xc6, 0x82, 0xf2, 0x73, 0x09, 0x56, 0x53,
	0xdf, 0x60, 0xbb, 0x08, 0x32, 0x32, 0xf0, 0x46, 0xbc, 0x1f, 0x8a, 0xed, 0x82, 0xba, 0x24, 0xf2,
	0x39, 0x47, 0xdf, 0xbd, 0xc7, 0x26, 0xb4, 0xc1, 0xba, 0xcb, 0x14, 0xc8, 0x77, 0x5e, 0x42, 0xda,
	0x4a, 0xd4, 0x48, 0x0f, 0x7a, 0x2d, 0x1a, 0x1b, 0xa7, 0xff, 0x58, 0x39, 0x0a, 0xcc, 0x2f, 0xcb,
	0xab, 0x4a, 0x82, 0x52, 0x4e, 0x3c, 0xb7, 0xa2, 0x02, 0xc9, 0xf3, 0x86, 0x77, 0xb9, 0xe6, 0x28,
	0xac, 0x95, 0x2c, 0xc9, 0xe8, 0xd1, 0x72, 0x17, 0x28, 0x5e, 0x78, 0x4d, 0x67, 0xe4, 0xa4, 0xe0,
	0xa2, 0x7a, 0x76, 0x84, 0x70, 0x10, 0x0f, 0xae, 0xfc, 0xe9, 0x24, 0x35, 0xd3, 0x45, 0x9d, 0xde,
	0x5a, 0x9d, 0xf9, 0x7d, 0xca, 0x1d, 0x92, 0xef, 0x01, 0x19, 0x31, 0x28, 0x51, 0x56, 0x0c, 0xde,
	0x36, 0xa0, 0x34, 0xbd, 0x26, 0x5e, 0x89, 0xb8, 0xe2, 0x60, 0x00, 0xc7, 0xf3, 0xe0, 0xeb, 0x27,
	0x1c, 0xff, 0x41, 0x16, 0xc6, 0x62, 0x2e, 0x42, 0x2f, 0xc8, 0xa1, 0xd2, 0x79, 0xb9, 0x0a, 0xf7,
	0xcd, 0x30, 0x3f, 0x35, 0x85, 0xee, 0x65, 0xbe, 0x06, 0x66, 0x1d, 0x7a, 0x49, 0x8e, 0x40, 0x68,
	0xc9, 0x41, 0x85, 0xc3, 0x78, 0xf8, 0x1f, 0xba, 0x13, 0x5a, 0x7e, 0xb2, 0xad, 0x97, 0x4c, 0xc8,
	0xe9, 0x76, 0x0f, 0xd5, 0xa2, 0x50, 0x30, 0x5d, 0x12, 0xff, 0x01, 0xeb, 0xce, 0x95, 0xa4, 0x37,
	0xc4, 0xb3, 0x01, 0x1a, 0x58, 0xc0, 0xce, 0xda, 0xd1, 0xd9, 0xae, 0x68, 0x19, 0xc9, 0xde, 0x3c,
	0x79, 0x8a, 0x6b, 0xae, 0x5f, 0x37, 0x45, 0x5a, 0xe2, 0x3a, 0x83, 0x8f, 0xb6, 0xc1, 0x0a, 0x54,
	0xe6, 0xfa, 0x98, 0x07, 0x28, 0x3c, 0x73, 0xa3, 0xb3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7,
	0x39, 0xc5, 0xf0, 0xae, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LogzServiceClient is the client API for LogzService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LogzServiceClient interface {
	Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error)
}

type logzServiceClient struct {
	cc *grpc.ClientConn
}

func NewLogzServiceClient(cc *grpc.ClientConn) LogzServiceClient {
	return &logzServiceClient{cc}
}

func (c *logzServiceClient) Record(ctx context.Context, in *RecordRequest, opts ...grpc.CallOption) (*RecordResponse, error) {
	out := new(RecordResponse)
	err := c.cc.Invoke(ctx, "/logz.LogzService/Record", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogzServiceServer is the server API for LogzService service.
type LogzServiceServer interface {
	Record(context.Context, *RecordRequest) (*RecordResponse, error)
}

func RegisterLogzServiceServer(s *grpc.Server, srv LogzServiceServer) {
	s.RegisterService(&_LogzService_serviceDesc, srv)
}

func _LogzService_Record_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogzServiceServer).Record(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logz.LogzService/Record",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogzServiceServer).Record(ctx, req.(*RecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LogzService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "logz.LogzService",
	HandlerType: (*LogzServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Record",
			Handler:    _LogzService_Record_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logz/service.proto",
}
