bind_address {
  host: "0.0.0.0"
  port: 4002
}
statusz_address {
  host: "0.0.0.0"
  port: 7002
}
logz_address {
  host: "0.0.0.0"
  port: 4001
}
default_features {
  name: "extra_addition"
  doc: "add an extra amount to the result of addition"
  default_value {
    i64: 0
  }
}
experimental_features {
  name: "small_extra_addition_experiment"
  doc: "add a small amount extra"
  mods {
    min: 0
    max: 99
  }
  features {
    flags {
      key: "extra_addition"
      value {
        i64: 1
      }
    }
  }
}
experimental_features {
  name: "large_extra_addition_experiment"
  doc: "add a large amount extra"
  mods {
    min: 100
    max: 199
  }
  features {
    flags {
      key: "extra_addition"
      value {
        i64: 100
      }
    }
  }
}