// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userz/cookie.proto

package userz

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Cookie struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	VisitorId            string   `protobuf:"bytes,2,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cookie) Reset()         { *m = Cookie{} }
func (m *Cookie) String() string { return proto.CompactTextString(m) }
func (*Cookie) ProtoMessage()    {}
func (*Cookie) Descriptor() ([]byte, []int) {
	return fileDescriptor_88a27416d790d51c, []int{0}
}

func (m *Cookie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cookie.Unmarshal(m, b)
}
func (m *Cookie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cookie.Marshal(b, m, deterministic)
}
func (m *Cookie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cookie.Merge(m, src)
}
func (m *Cookie) XXX_Size() int {
	return xxx_messageInfo_Cookie.Size(m)
}
func (m *Cookie) XXX_DiscardUnknown() {
	xxx_messageInfo_Cookie.DiscardUnknown(m)
}

var xxx_messageInfo_Cookie proto.InternalMessageInfo

func (m *Cookie) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *Cookie) GetVisitorId() string {
	if m != nil {
		return m.VisitorId
	}
	return ""
}

func (m *Cookie) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterType((*Cookie)(nil), "userz.Cookie")
}

func init() { proto.RegisterFile("userz/cookie.proto", fileDescriptor_88a27416d790d51c) }

var fileDescriptor_88a27416d790d51c = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x2d, 0x4e, 0x2d,
	0xaa, 0xd2, 0x4f, 0xce, 0xcf, 0xcf, 0xce, 0x4c, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x05, 0x8b, 0x29, 0xc5, 0x73, 0xb1, 0x39, 0x83, 0x85, 0x85, 0x64, 0xb9, 0xb8, 0x8a, 0x53, 0x8b,
	0x8b, 0x33, 0xf3, 0xf3, 0xe2, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x38, 0xa1,
	0x22, 0x9e, 0x29, 0x20, 0xe9, 0xb2, 0xcc, 0xe2, 0xcc, 0x92, 0xfc, 0x22, 0x90, 0x34, 0x13, 0x44,
	0x1a, 0x2a, 0xe2, 0x99, 0x22, 0x24, 0xce, 0xc5, 0x0e, 0x32, 0x10, 0x24, 0xc7, 0x0c, 0x96, 0x63,
	0x03, 0x71, 0x3d, 0x53, 0x9c, 0x94, 0xa3, 0x14, 0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92,
	0xf3, 0x73, 0xf5, 0x53, 0x2b, 0x0a, 0x72, 0xf2, 0x53, 0x52, 0x8b, 0xf5, 0x8b, 0x53, 0x8b, 0xca,
	0x32, 0xf3, 0xd2, 0xf5, 0xc1, 0xae, 0x48, 0x62, 0x03, 0xbb, 0xc9, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0x27, 0x65, 0xdc, 0xcb, 0xa9, 0x00, 0x00, 0x00,
}
