// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userz/service.proto

package userz

import (
	fmt "fmt"
	proto1 "github.com/explodes/serving/proto"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginResponse_LoginFailure_Reason int32

const (
	LoginResponse_LoginFailure_UNKNOWN   LoginResponse_LoginFailure_Reason = 0
	LoginResponse_LoginFailure_BAD_LOGIN LoginResponse_LoginFailure_Reason = 1
)

var LoginResponse_LoginFailure_Reason_name = map[int32]string{
	0: "UNKNOWN",
	1: "BAD_LOGIN",
}

var LoginResponse_LoginFailure_Reason_value = map[string]int32{
	"UNKNOWN":   0,
	"BAD_LOGIN": 1,
}

func (x LoginResponse_LoginFailure_Reason) String() string {
	return proto.EnumName(LoginResponse_LoginFailure_Reason_name, int32(x))
}

func (LoginResponse_LoginFailure_Reason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7c83c3aa6ff03d73, []int{2, 1, 0}
}

type ValidateResponse_ValidateResult int32

const (
	ValidateResponse_UNKNOWN ValidateResponse_ValidateResult = 0
	ValidateResponse_SUCCESS ValidateResponse_ValidateResult = 1
	ValidateResponse_INVALID ValidateResponse_ValidateResult = 2
)

var ValidateResponse_ValidateResult_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	2: "INVALID",
}

var ValidateResponse_ValidateResult_value = map[string]int32{
	"UNKNOWN": 0,
	"SUCCESS": 1,
	"INVALID": 2,
}

func (x ValidateResponse_ValidateResult) String() string {
	return proto.EnumName(ValidateResponse_ValidateResult_name, int32(x))
}

func (ValidateResponse_ValidateResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7c83c3aa6ff03d73, []int{4, 0}
}

type UserzConfig struct {
	BindAddress          *proto1.Address `protobuf:"bytes,1,opt,name=bind_address,json=bindAddress,proto3" json:"bind_address,omitempty"`
	JsonBindAddress      *proto1.Address `protobuf:"bytes,2,opt,name=json_bind_address,json=jsonBindAddress,proto3" json:"json_bind_address,omitempty"`
	LogzAddress          *proto1.Address `protobuf:"bytes,3,opt,name=logz_address,json=logzAddress,proto3" json:"logz_address,omitempty"`
	ExpzAddress          *proto1.Address `protobuf:"bytes,4,opt,name=expz_address,json=expzAddress,proto3" json:"expz_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserzConfig) Reset()         { *m = UserzConfig{} }
func (m *UserzConfig) String() string { return proto.CompactTextString(m) }
func (*UserzConfig) ProtoMessage()    {}
func (*UserzConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c83c3aa6ff03d73, []int{0}
}

func (m *UserzConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserzConfig.Unmarshal(m, b)
}
func (m *UserzConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserzConfig.Marshal(b, m, deterministic)
}
func (m *UserzConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserzConfig.Merge(m, src)
}
func (m *UserzConfig) XXX_Size() int {
	return xxx_messageInfo_UserzConfig.Size(m)
}
func (m *UserzConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_UserzConfig.DiscardUnknown(m)
}

var xxx_messageInfo_UserzConfig proto.InternalMessageInfo

func (m *UserzConfig) GetBindAddress() *proto1.Address {
	if m != nil {
		return m.BindAddress
	}
	return nil
}

func (m *UserzConfig) GetJsonBindAddress() *proto1.Address {
	if m != nil {
		return m.JsonBindAddress
	}
	return nil
}

func (m *UserzConfig) GetLogzAddress() *proto1.Address {
	if m != nil {
		return m.LogzAddress
	}
	return nil
}

func (m *UserzConfig) GetExpzAddress() *proto1.Address {
	if m != nil {
		return m.ExpzAddress
	}
	return nil
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c83c3aa6ff03d73, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	// Types that are valid to be assigned to Result:
	//	*LoginResponse_Success
	//	*LoginResponse_Failure
	Result               isLoginResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c83c3aa6ff03d73, []int{2}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

type isLoginResponse_Result interface {
	isLoginResponse_Result()
}

type LoginResponse_Success struct {
	Success *LoginResponse_LoginSuccess `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type LoginResponse_Failure struct {
	Failure *LoginResponse_LoginFailure `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*LoginResponse_Success) isLoginResponse_Result() {}

func (*LoginResponse_Failure) isLoginResponse_Result() {}

func (m *LoginResponse) GetResult() isLoginResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *LoginResponse) GetSuccess() *LoginResponse_LoginSuccess {
	if x, ok := m.GetResult().(*LoginResponse_Success); ok {
		return x.Success
	}
	return nil
}

func (m *LoginResponse) GetFailure() *LoginResponse_LoginFailure {
	if x, ok := m.GetResult().(*LoginResponse_Failure); ok {
		return x.Failure
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*LoginResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _LoginResponse_OneofMarshaler, _LoginResponse_OneofUnmarshaler, _LoginResponse_OneofSizer, []interface{}{
		(*LoginResponse_Success)(nil),
		(*LoginResponse_Failure)(nil),
	}
}

func _LoginResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*LoginResponse)
	// result
	switch x := m.Result.(type) {
	case *LoginResponse_Success:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Success); err != nil {
			return err
		}
	case *LoginResponse_Failure:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Failure); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("LoginResponse.Result has unexpected type %T", x)
	}
	return nil
}

func _LoginResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*LoginResponse)
	switch tag {
	case 1: // result.success
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LoginResponse_LoginSuccess)
		err := b.DecodeMessage(msg)
		m.Result = &LoginResponse_Success{msg}
		return true, err
	case 2: // result.failure
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LoginResponse_LoginFailure)
		err := b.DecodeMessage(msg)
		m.Result = &LoginResponse_Failure{msg}
		return true, err
	default:
		return false, nil
	}
}

func _LoginResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*LoginResponse)
	// result
	switch x := m.Result.(type) {
	case *LoginResponse_Success:
		s := proto.Size(x.Success)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *LoginResponse_Failure:
		s := proto.Size(x.Failure)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type LoginResponse_LoginSuccess struct {
	Cookie               string   `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse_LoginSuccess) Reset()         { *m = LoginResponse_LoginSuccess{} }
func (m *LoginResponse_LoginSuccess) String() string { return proto.CompactTextString(m) }
func (*LoginResponse_LoginSuccess) ProtoMessage()    {}
func (*LoginResponse_LoginSuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c83c3aa6ff03d73, []int{2, 0}
}

func (m *LoginResponse_LoginSuccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse_LoginSuccess.Unmarshal(m, b)
}
func (m *LoginResponse_LoginSuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse_LoginSuccess.Marshal(b, m, deterministic)
}
func (m *LoginResponse_LoginSuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse_LoginSuccess.Merge(m, src)
}
func (m *LoginResponse_LoginSuccess) XXX_Size() int {
	return xxx_messageInfo_LoginResponse_LoginSuccess.Size(m)
}
func (m *LoginResponse_LoginSuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse_LoginSuccess.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse_LoginSuccess proto.InternalMessageInfo

func (m *LoginResponse_LoginSuccess) GetCookie() string {
	if m != nil {
		return m.Cookie
	}
	return ""
}

type LoginResponse_LoginFailure struct {
	Reason               LoginResponse_LoginFailure_Reason `protobuf:"varint,1,opt,name=reason,proto3,enum=userz.LoginResponse_LoginFailure_Reason" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *LoginResponse_LoginFailure) Reset()         { *m = LoginResponse_LoginFailure{} }
func (m *LoginResponse_LoginFailure) String() string { return proto.CompactTextString(m) }
func (*LoginResponse_LoginFailure) ProtoMessage()    {}
func (*LoginResponse_LoginFailure) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c83c3aa6ff03d73, []int{2, 1}
}

func (m *LoginResponse_LoginFailure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse_LoginFailure.Unmarshal(m, b)
}
func (m *LoginResponse_LoginFailure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse_LoginFailure.Marshal(b, m, deterministic)
}
func (m *LoginResponse_LoginFailure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse_LoginFailure.Merge(m, src)
}
func (m *LoginResponse_LoginFailure) XXX_Size() int {
	return xxx_messageInfo_LoginResponse_LoginFailure.Size(m)
}
func (m *LoginResponse_LoginFailure) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse_LoginFailure.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse_LoginFailure proto.InternalMessageInfo

func (m *LoginResponse_LoginFailure) GetReason() LoginResponse_LoginFailure_Reason {
	if m != nil {
		return m.Reason
	}
	return LoginResponse_LoginFailure_UNKNOWN
}

type ValidateRequest struct {
	Cookie               string   `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c83c3aa6ff03d73, []int{3}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetCookie() string {
	if m != nil {
		return m.Cookie
	}
	return ""
}

type ValidateResponse struct {
	Result               ValidateResponse_ValidateResult `protobuf:"varint,1,opt,name=result,proto3,enum=userz.ValidateResponse_ValidateResult" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ValidateResponse) Reset()         { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()    {}
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c83c3aa6ff03d73, []int{4}
}

func (m *ValidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateResponse.Unmarshal(m, b)
}
func (m *ValidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateResponse.Marshal(b, m, deterministic)
}
func (m *ValidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateResponse.Merge(m, src)
}
func (m *ValidateResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateResponse.Size(m)
}
func (m *ValidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateResponse proto.InternalMessageInfo

func (m *ValidateResponse) GetResult() ValidateResponse_ValidateResult {
	if m != nil {
		return m.Result
	}
	return ValidateResponse_UNKNOWN
}

func init() {
	proto.RegisterEnum("userz.LoginResponse_LoginFailure_Reason", LoginResponse_LoginFailure_Reason_name, LoginResponse_LoginFailure_Reason_value)
	proto.RegisterEnum("userz.ValidateResponse_ValidateResult", ValidateResponse_ValidateResult_name, ValidateResponse_ValidateResult_value)
	proto.RegisterType((*UserzConfig)(nil), "userz.UserzConfig")
	proto.RegisterType((*LoginRequest)(nil), "userz.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "userz.LoginResponse")
	proto.RegisterType((*LoginResponse_LoginSuccess)(nil), "userz.LoginResponse.LoginSuccess")
	proto.RegisterType((*LoginResponse_LoginFailure)(nil), "userz.LoginResponse.LoginFailure")
	proto.RegisterType((*ValidateRequest)(nil), "userz.ValidateRequest")
	proto.RegisterType((*ValidateResponse)(nil), "userz.ValidateResponse")
}

func init() { proto.RegisterFile("userz/service.proto", fileDescriptor_7c83c3aa6ff03d73) }

var fileDescriptor_7c83c3aa6ff03d73 = []byte{
	// 525 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcd, 0x6e, 0xd3, 0x4e,
	0x14, 0xc5, 0xe3, 0xfc, 0xff, 0xcd, 0xc7, 0x4d, 0xda, 0x98, 0x09, 0x82, 0xe2, 0x15, 0x35, 0x08,
	0x55, 0x42, 0x72, 0xa4, 0x04, 0x89, 0x05, 0xb4, 0x22, 0x49, 0x29, 0x44, 0x44, 0xae, 0x64, 0x2b,
	0x45, 0x62, 0x13, 0x39, 0xf6, 0xd4, 0x0c, 0xb8, 0x1e, 0xe3, 0xb1, 0x4b, 0x95, 0x25, 0x2c, 0x79,
	0x1e, 0xde, 0x82, 0x27, 0xe1, 0x29, 0xd0, 0x7c, 0x38, 0x89, 0x81, 0x80, 0x58, 0xde, 0x7b, 0xcf,
	0xef, 0xce, 0x9c, 0x33, 0xb2, 0xa1, 0x9b, 0x33, 0x9c, 0x2e, 0x7b, 0x0c, 0xa7, 0x57, 0xc4, 0xc7,
	0x56, 0x92, 0xd2, 0x8c, 0xa2, 0x1d, 0xd1, 0x34, 0xee, 0x88, 0x8a, 0xcf, 0x88, 0x17, 0x91, 0xa5,
	0x97, 0x11, 0x1a, 0x4b, 0x85, 0xd1, 0x95, 0x23, 0x2f, 0x08, 0x52, 0xcc, 0x98, 0x6c, 0x9a, 0xdf,
	0x35, 0x68, 0xcd, 0x38, 0x39, 0xa6, 0xf1, 0x05, 0x09, 0xd1, 0x00, 0xda, 0x0b, 0x12, 0x07, 0x73,
	0xa5, 0xda, 0xd7, 0xee, 0x6a, 0x87, 0xad, 0xbe, 0x6e, 0x89, 0xc3, 0xe2, 0xd0, 0x1a, 0xca, 0xbe,
	0xd3, 0xe2, 0x2a, 0x55, 0xa0, 0xa7, 0x70, 0xe3, 0x1d, 0xa3, 0xf1, 0xbc, 0x44, 0x56, 0xb7, 0x90,
	0x1d, 0x2e, 0x1d, 0x6d, 0xd0, 0x03, 0x68, 0x47, 0x34, 0x5c, 0xae, 0xc0, 0xff, 0xb6, 0x1d, 0xc9,
	0x55, 0x1b, 0x10, 0xbe, 0x4e, 0xd6, 0xd0, 0xff, 0xdb, 0x20, 0xae, 0x52, 0x85, 0x79, 0x0a, 0xed,
	0x29, 0x0d, 0x49, 0xec, 0xe0, 0x0f, 0x39, 0x66, 0x19, 0x32, 0xa0, 0xc1, 0x53, 0x8b, 0xbd, 0x4b,
	0x2c, 0x8c, 0x36, 0x9d, 0x55, 0xcd, 0x67, 0x89, 0xc7, 0xd8, 0x47, 0x9a, 0x06, 0xc2, 0x4a, 0xd3,
	0x59, 0xd5, 0xe6, 0xb7, 0x2a, 0xec, 0xaa, 0x45, 0x2c, 0xa1, 0x31, 0xc3, 0xe8, 0x08, 0xea, 0x2c,
	0xf7, 0xfd, 0x75, 0x62, 0x07, 0x96, 0x78, 0x0f, 0xab, 0x24, 0x93, 0x95, 0x2b, 0x85, 0x2f, 0x2b,
	0x4e, 0xc1, 0x70, 0xfc, 0xc2, 0x23, 0x51, 0x9e, 0x62, 0x15, 0xdb, 0x1f, 0xf0, 0x53, 0x29, 0xe4,
	0xb8, 0x62, 0x8c, 0x27, 0xca, 0x97, 0xda, 0x8c, 0x1e, 0x42, 0xcd, 0xa7, 0xf4, 0x3d, 0x51, 0xae,
	0x46, 0xdd, 0x4f, 0x5f, 0xf7, 0x3b, 0xab, 0x68, 0xc6, 0x62, 0xe4, 0x28, 0x89, 0x71, 0xa5, 0x60,
	0xb5, 0x17, 0x3d, 0x83, 0x5a, 0x8a, 0x3d, 0x46, 0x63, 0x01, 0xef, 0xf5, 0x0f, 0xff, 0x7a, 0x15,
	0xcb, 0x11, 0x7a, 0x47, 0x71, 0xe6, 0x7d, 0xa8, 0xc9, 0x0e, 0x6a, 0x41, 0x7d, 0x66, 0xbf, 0xb2,
	0xcf, 0x5e, 0xdb, 0x7a, 0x05, 0xed, 0x42, 0x73, 0x34, 0x3c, 0x99, 0x4f, 0xcf, 0x5e, 0x4c, 0x6c,
	0x5d, 0x1b, 0x35, 0xf8, 0x39, 0x2c, 0x8f, 0x32, 0xf3, 0x18, 0x3a, 0xe7, 0x5e, 0x44, 0x02, 0x2f,
	0xc3, 0xc5, 0xcb, 0xfc, 0x8b, 0x03, 0xf3, 0x8b, 0x06, 0xfa, 0x7a, 0x81, 0x7a, 0x91, 0xe3, 0x62,
	0xbd, 0xb2, 0xf1, 0x40, 0xd9, 0xf8, 0x59, 0xb8, 0xd9, 0xc8, 0xa3, 0xcc, 0x29, 0x2e, 0xf5, 0x18,
	0xf6, 0xca, 0x93, 0xb2, 0x99, 0x16, 0xd4, 0xdd, 0xd9, 0x78, 0xfc, 0xdc, 0x75, 0x75, 0x8d, 0x17,
	0x13, 0xfb, 0x7c, 0x38, 0x9d, 0x9c, 0xe8, 0xd5, 0xfe, 0x67, 0x0d, 0xda, 0xe2, 0x8b, 0x72, 0xe5,
	0xf7, 0x89, 0x1e, 0xc1, 0x8e, 0x48, 0x0b, 0x75, 0xcb, 0x49, 0x0a, 0xa7, 0xc6, 0xcd, 0xdf, 0xc5,
	0x6b, 0x56, 0xd0, 0x11, 0x34, 0x8a, 0xf3, 0xd1, 0xad, 0x5f, 0xee, 0x2e, 0xd9, 0xdb, 0x5b, 0x3c,
	0x99, 0x95, 0xd1, 0xbd, 0x37, 0x07, 0x21, 0xc9, 0xde, 0xe6, 0x0b, 0xcb, 0xa7, 0x97, 0x3d, 0x7c,
	0x9d, 0x44, 0x34, 0xc0, 0xac, 0xa7, 0x12, 0xec, 0x09, 0x6e, 0x51, 0x13, 0xff, 0x80, 0xc1, 0x8f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x05, 0x31, 0x8d, 0xfd, 0x51, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserzServiceClient is the client API for UserzService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserzServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type userzServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserzServiceClient(cc *grpc.ClientConn) UserzServiceClient {
	return &userzServiceClient{cc}
}

func (c *userzServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/userz.UserzService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userzServiceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, "/userz.UserzService/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserzServiceServer is the server API for UserzService service.
type UserzServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
}

func RegisterUserzServiceServer(s *grpc.Server, srv UserzServiceServer) {
	s.RegisterService(&_UserzService_serviceDesc, srv)
}

func _UserzService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserzServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userz.UserzService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserzServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserzService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserzServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userz.UserzService/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserzServiceServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserzService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "userz.UserzService",
	HandlerType: (*UserzServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserzService_Login_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _UserzService_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userz/service.proto",
}
