// Code generated by protoc-gen-go. DO NOT EDIT.
// source: timestamp/timestamp.proto

package timestamp

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Timestamp struct {
	Milliseconds         int64    `protobuf:"varint,1,opt,name=milliseconds,proto3" json:"milliseconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9611dc94425ece5d, []int{0}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

func (m *Timestamp) GetMilliseconds() int64 {
	if m != nil {
		return m.Milliseconds
	}
	return 0
}

func init() {
	proto.RegisterType((*Timestamp)(nil), "serving.proto.Timestamp")
}

func init() { proto.RegisterFile("timestamp/timestamp.proto", fileDescriptor_9611dc94425ece5d) }

var fileDescriptor_9611dc94425ece5d = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0xc9, 0xcc, 0x4d,
	0x2d, 0x2e, 0x49, 0xcc, 0x2d, 0xd0, 0x87, 0xb3, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x78,
	0x8b, 0x53, 0x8b, 0xca, 0x32, 0xf3, 0xd2, 0x21, 0x5c, 0x25, 0x7d, 0x2e, 0xce, 0x10, 0x98, 0x0a,
	0x21, 0x25, 0x2e, 0x9e, 0xdc, 0xcc, 0x9c, 0x9c, 0xcc, 0xe2, 0xd4, 0xe4, 0xfc, 0xbc, 0x94, 0x62,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x14, 0x31, 0x27, 0xf5, 0x28, 0xd5, 0xf4, 0xcc, 0x92,
	0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0xd4, 0x8a, 0x82, 0x9c, 0xfc, 0x94, 0xd4, 0x62,
	0x7d, 0xa8, 0xa9, 0x08, 0xeb, 0x92, 0xd8, 0xc0, 0x16, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x24, 0xce, 0x22, 0xa3, 0x8c, 0x00, 0x00, 0x00,
}
