// Code generated by protoc-gen-go. DO NOT EDIT.
// source: statusz/statusz.proto

package statusz

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetStatuszRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatuszRequest) Reset()         { *m = GetStatuszRequest{} }
func (m *GetStatuszRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatuszRequest) ProtoMessage()    {}
func (*GetStatuszRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_268982af76b02c46, []int{0}
}

func (m *GetStatuszRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatuszRequest.Unmarshal(m, b)
}
func (m *GetStatuszRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatuszRequest.Marshal(b, m, deterministic)
}
func (m *GetStatuszRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatuszRequest.Merge(m, src)
}
func (m *GetStatuszRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatuszRequest.Size(m)
}
func (m *GetStatuszRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatuszRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatuszRequest proto.InternalMessageInfo

type GetStatuszResponse struct {
	Statusz              *Statusz `protobuf:"bytes,1,opt,name=statusz,proto3" json:"statusz,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatuszResponse) Reset()         { *m = GetStatuszResponse{} }
func (m *GetStatuszResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatuszResponse) ProtoMessage()    {}
func (*GetStatuszResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_268982af76b02c46, []int{1}
}

func (m *GetStatuszResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatuszResponse.Unmarshal(m, b)
}
func (m *GetStatuszResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatuszResponse.Marshal(b, m, deterministic)
}
func (m *GetStatuszResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatuszResponse.Merge(m, src)
}
func (m *GetStatuszResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatuszResponse.Size(m)
}
func (m *GetStatuszResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatuszResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatuszResponse proto.InternalMessageInfo

func (m *GetStatuszResponse) GetStatusz() *Statusz {
	if m != nil {
		return m.Statusz
	}
	return nil
}

type Statusz struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Statusz) Reset()         { *m = Statusz{} }
func (m *Statusz) String() string { return proto.CompactTextString(m) }
func (*Statusz) ProtoMessage()    {}
func (*Statusz) Descriptor() ([]byte, []int) {
	return fileDescriptor_268982af76b02c46, []int{2}
}

func (m *Statusz) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statusz.Unmarshal(m, b)
}
func (m *Statusz) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statusz.Marshal(b, m, deterministic)
}
func (m *Statusz) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statusz.Merge(m, src)
}
func (m *Statusz) XXX_Size() int {
	return xxx_messageInfo_Statusz.Size(m)
}
func (m *Statusz) XXX_DiscardUnknown() {
	xxx_messageInfo_Statusz.DiscardUnknown(m)
}

var xxx_messageInfo_Statusz proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetStatuszRequest)(nil), "serving.statusz.GetStatuszRequest")
	proto.RegisterType((*GetStatuszResponse)(nil), "serving.statusz.GetStatuszResponse")
	proto.RegisterType((*Statusz)(nil), "serving.statusz.Statusz")
}

func init() { proto.RegisterFile("statusz/statusz.proto", fileDescriptor_268982af76b02c46) }

var fileDescriptor_268982af76b02c46 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x2e, 0x49, 0x2c,
	0x29, 0x2d, 0xae, 0xd2, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xfc, 0xc5, 0xa9,
	0x45, 0x65, 0x99, 0x79, 0xe9, 0x7a, 0x50, 0x61, 0x25, 0x61, 0x2e, 0x41, 0xf7, 0xd4, 0x92, 0x60,
	0x08, 0x2f, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44, 0xc9, 0x83, 0x4b, 0x08, 0x59, 0xb0, 0xb8,
	0x20, 0x3f, 0xaf, 0x38, 0x55, 0xc8, 0x88, 0x8b, 0x1d, 0xaa, 0x4b, 0x82, 0x51, 0x81, 0x51, 0x83,
	0xdb, 0x48, 0x42, 0x0f, 0xcd, 0x34, 0x3d, 0x98, 0x16, 0x98, 0x42, 0x25, 0x4e, 0x2e, 0x76, 0xa8,
	0x98, 0x51, 0x26, 0x17, 0x1f, 0x94, 0x19, 0x0c, 0xd2, 0x95, 0x9c, 0x2a, 0x14, 0xce, 0xc5, 0x85,
	0xb0, 0x46, 0x48, 0x09, 0xc3, 0x34, 0x0c, 0x87, 0x49, 0x29, 0xe3, 0x55, 0x03, 0x71, 0xa7, 0x12,
	0x83, 0x93, 0x6a, 0x94, 0x72, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e,
	0x6a, 0x45, 0x41, 0x4e, 0x7e, 0x4a, 0x6a, 0xb1, 0x3e, 0x54, 0x2f, 0x2c, 0x48, 0x92, 0xd8, 0xc0,
	0x61, 0x62, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xd5, 0x02, 0x6d, 0x2c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatuszServiceClient is the client API for StatuszService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatuszServiceClient interface {
	GetStatusz(ctx context.Context, in *GetStatuszRequest, opts ...grpc.CallOption) (*GetStatuszResponse, error)
}

type statuszServiceClient struct {
	cc *grpc.ClientConn
}

func NewStatuszServiceClient(cc *grpc.ClientConn) StatuszServiceClient {
	return &statuszServiceClient{cc}
}

func (c *statuszServiceClient) GetStatusz(ctx context.Context, in *GetStatuszRequest, opts ...grpc.CallOption) (*GetStatuszResponse, error) {
	out := new(GetStatuszResponse)
	err := c.cc.Invoke(ctx, "/serving.statusz.StatuszService/GetStatusz", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatuszServiceServer is the server API for StatuszService service.
type StatuszServiceServer interface {
	GetStatusz(context.Context, *GetStatuszRequest) (*GetStatuszResponse, error)
}

func RegisterStatuszServiceServer(s *grpc.Server, srv StatuszServiceServer) {
	s.RegisterService(&_StatuszService_serviceDesc, srv)
}

func _StatuszService_GetStatusz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatuszRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatuszServiceServer).GetStatusz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/serving.statusz.StatuszService/GetStatusz",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatuszServiceServer).GetStatusz(ctx, req.(*GetStatuszRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StatuszService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "serving.statusz.StatuszService",
	HandlerType: (*StatuszServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatusz",
			Handler:    _StatuszService_GetStatusz_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "statusz/statusz.proto",
}
