// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/address.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Address struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_75bc2f2270897675, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Address) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type GrpcServer struct {
	Address              *Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcServer) Reset()         { *m = GrpcServer{} }
func (m *GrpcServer) String() string { return proto.CompactTextString(m) }
func (*GrpcServer) ProtoMessage()    {}
func (*GrpcServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_75bc2f2270897675, []int{1}
}

func (m *GrpcServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcServer.Unmarshal(m, b)
}
func (m *GrpcServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcServer.Marshal(b, m, deterministic)
}
func (m *GrpcServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcServer.Merge(m, src)
}
func (m *GrpcServer) XXX_Size() int {
	return xxx_messageInfo_GrpcServer.Size(m)
}
func (m *GrpcServer) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcServer.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcServer proto.InternalMessageInfo

func (m *GrpcServer) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func init() {
	proto.RegisterType((*Address)(nil), "serving.Address")
	proto.RegisterType((*GrpcServer)(nil), "serving.GrpcServer")
}

func init() { proto.RegisterFile("proto/address.proto", fileDescriptor_75bc2f2270897675) }

var fileDescriptor_75bc2f2270897675 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4c, 0x49, 0x29, 0x4a, 0x2d, 0x2e, 0xd6, 0x03, 0xf3, 0x84, 0xd8, 0x8b, 0x53,
	0x8b, 0xca, 0x32, 0xf3, 0xd2, 0x95, 0x0c, 0xb9, 0xd8, 0x1d, 0x21, 0x32, 0x42, 0x42, 0x5c, 0x2c,
	0x19, 0xf9, 0xc5, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0x36, 0x48, 0xac, 0x20,
	0xbf, 0xa8, 0x44, 0x82, 0x49, 0x81, 0x51, 0x83, 0x37, 0x08, 0xcc, 0x56, 0xb2, 0xe0, 0xe2, 0x72,
	0x2f, 0x2a, 0x48, 0x0e, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0x12, 0xd2, 0xe2, 0x62, 0x87, 0x1a, 0x0d,
	0xd6, 0xc8, 0x6d, 0x24, 0xa0, 0x07, 0x35, 0x5b, 0x0f, 0x6a, 0x70, 0x10, 0x4c, 0x81, 0x93, 0x72,
	0x94, 0x62, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x7e, 0x6a, 0x45, 0x41,
	0x4e, 0x7e, 0x4a, 0x6a, 0xb1, 0x3e, 0x54, 0xbd, 0x3e, 0xd8, 0x69, 0x49, 0x6c, 0x60, 0xca, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x2f, 0x7c, 0x5f, 0xb8, 0x00, 0x00, 0x00,
}
