// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/address.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Address struct {
	Host                 string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 uint32   `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_75bc2f2270897675, []int{0}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Address) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type GrpcServer struct {
	Address *Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// If specified, use an exponential backoff strategy with a
	// default maximum delay of 20 seconds.
	ExponentialBackoff *GrpcServer_ExponentialBackoff `protobuf:"bytes,2,opt,name=exponential_backoff,json=exponentialBackoff,proto3" json:"exponential_backoff,omitempty"`
	// If specified, gzip will be used using a compression level
	// optimized for speed.
	EnableGzip           bool     `protobuf:"varint,3,opt,name=enable_gzip,json=enableGzip,proto3" json:"enable_gzip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GrpcServer) Reset()         { *m = GrpcServer{} }
func (m *GrpcServer) String() string { return proto.CompactTextString(m) }
func (*GrpcServer) ProtoMessage()    {}
func (*GrpcServer) Descriptor() ([]byte, []int) {
	return fileDescriptor_75bc2f2270897675, []int{1}
}

func (m *GrpcServer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcServer.Unmarshal(m, b)
}
func (m *GrpcServer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcServer.Marshal(b, m, deterministic)
}
func (m *GrpcServer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcServer.Merge(m, src)
}
func (m *GrpcServer) XXX_Size() int {
	return xxx_messageInfo_GrpcServer.Size(m)
}
func (m *GrpcServer) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcServer.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcServer proto.InternalMessageInfo

func (m *GrpcServer) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *GrpcServer) GetExponentialBackoff() *GrpcServer_ExponentialBackoff {
	if m != nil {
		return m.ExponentialBackoff
	}
	return nil
}

func (m *GrpcServer) GetEnableGzip() bool {
	if m != nil {
		return m.EnableGzip
	}
	return false
}

type GrpcServer_ExponentialBackoff struct {
	// Override the max delay of the exponential backoff.
	// By default, this value is 20 seconds.
	OverrideMaxDelay     *Duration `protobuf:"bytes,1,opt,name=override_max_delay,json=overrideMaxDelay,proto3" json:"override_max_delay,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GrpcServer_ExponentialBackoff) Reset()         { *m = GrpcServer_ExponentialBackoff{} }
func (m *GrpcServer_ExponentialBackoff) String() string { return proto.CompactTextString(m) }
func (*GrpcServer_ExponentialBackoff) ProtoMessage()    {}
func (*GrpcServer_ExponentialBackoff) Descriptor() ([]byte, []int) {
	return fileDescriptor_75bc2f2270897675, []int{1, 0}
}

func (m *GrpcServer_ExponentialBackoff) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GrpcServer_ExponentialBackoff.Unmarshal(m, b)
}
func (m *GrpcServer_ExponentialBackoff) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GrpcServer_ExponentialBackoff.Marshal(b, m, deterministic)
}
func (m *GrpcServer_ExponentialBackoff) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GrpcServer_ExponentialBackoff.Merge(m, src)
}
func (m *GrpcServer_ExponentialBackoff) XXX_Size() int {
	return xxx_messageInfo_GrpcServer_ExponentialBackoff.Size(m)
}
func (m *GrpcServer_ExponentialBackoff) XXX_DiscardUnknown() {
	xxx_messageInfo_GrpcServer_ExponentialBackoff.DiscardUnknown(m)
}

var xxx_messageInfo_GrpcServer_ExponentialBackoff proto.InternalMessageInfo

func (m *GrpcServer_ExponentialBackoff) GetOverrideMaxDelay() *Duration {
	if m != nil {
		return m.OverrideMaxDelay
	}
	return nil
}

func init() {
	proto.RegisterType((*Address)(nil), "serving.Address")
	proto.RegisterType((*GrpcServer)(nil), "serving.GrpcServer")
	proto.RegisterType((*GrpcServer_ExponentialBackoff)(nil), "serving.GrpcServer.ExponentialBackoff")
}

func init() { proto.RegisterFile("proto/address.proto", fileDescriptor_75bc2f2270897675) }

var fileDescriptor_75bc2f2270897675 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0xe9, 0x14, 0xab, 0xaf, 0x08, 0x35, 0xbb, 0x94, 0x5d, 0xac, 0x13, 0xa4, 0x78, 0x68,
	0x71, 0x7e, 0x00, 0x71, 0x4c, 0x76, 0xf2, 0x12, 0x11, 0xc1, 0x4b, 0x49, 0xdb, 0xb7, 0x2e, 0xd8,
	0x36, 0x21, 0xcd, 0x4a, 0xdd, 0x37, 0xf0, 0x5b, 0xcb, 0xd2, 0x6c, 0x3b, 0xec, 0x94, 0x97, 0xff,
	0xfb, 0xfd, 0xff, 0x2f, 0x79, 0x30, 0x96, 0x4a, 0x68, 0x91, 0xb0, 0xa2, 0x50, 0xd8, 0xb6, 0xb1,
	0xb9, 0x11, 0xb7, 0x45, 0xd5, 0xf1, 0xa6, 0x9c, 0xf8, 0x43, 0x57, 0xf3, 0x1a, 0x87, 0xd6, 0xf4,
	0x09, 0xdc, 0xd7, 0x81, 0x25, 0x04, 0xce, 0xd7, 0xa2, 0xd5, 0x81, 0x13, 0x3a, 0xd1, 0x15, 0x35,
	0xf5, 0x4e, 0x93, 0x42, 0xe9, 0x60, 0x14, 0x3a, 0xd1, 0x35, 0x35, 0xf5, 0xf4, 0x6f, 0x04, 0xb0,
	0x54, 0x32, 0xff, 0x40, 0xd5, 0xa1, 0x22, 0x8f, 0xe0, 0xda, 0x69, 0xc6, 0xe9, 0xcd, 0xfc, 0xd8,
	0x8e, 0x8b, 0x6d, 0x32, 0xdd, 0x03, 0xe4, 0x0b, 0xc6, 0xd8, 0x4b, 0xd1, 0x60, 0xa3, 0x39, 0xab,
	0xd2, 0x8c, 0xe5, 0x3f, 0x62, 0xb5, 0x32, 0xe9, 0xde, 0xec, 0xe1, 0xe0, 0x3b, 0xa6, 0xc7, 0x6f,
	0x47, 0x7c, 0x3e, 0xd0, 0x94, 0xe0, 0x89, 0x46, 0x6e, 0xc1, 0xc3, 0x86, 0x65, 0x15, 0xa6, 0xe5,
	0x96, 0xcb, 0xe0, 0x2c, 0x74, 0xa2, 0x4b, 0x0a, 0x83, 0xb4, 0xdc, 0x72, 0x39, 0xf9, 0x04, 0x72,
	0x1a, 0x45, 0x5e, 0x80, 0x88, 0x0e, 0x95, 0xe2, 0x05, 0xa6, 0x35, 0xeb, 0xd3, 0x02, 0x2b, 0xf6,
	0x6b, 0xbf, 0x71, 0x73, 0x78, 0xce, 0x62, 0xa3, 0x98, 0xe6, 0xa2, 0xa1, 0xfe, 0x1e, 0x7e, 0x67,
	0xfd, 0x62, 0x87, 0xce, 0xef, 0xbf, 0xef, 0x4a, 0xae, 0xd7, 0x9b, 0x2c, 0xce, 0x45, 0x9d, 0x60,
	0x2f, 0x2b, 0x51, 0x60, 0x9b, 0x58, 0x67, 0x62, 0x76, 0x9c, 0x5d, 0x98, 0xe3, 0xf9, 0x3f, 0x00,
	0x00, 0xff, 0xff, 0x18, 0x0b, 0x6e, 0x43, 0x9c, 0x01, 0x00, 0x00,
}
