// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/time.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Timestamp struct {
	// Types that are valid to be assigned to Unit:
	//	*Timestamp_Nanoseconds
	//	*Timestamp_Milliseconds
	//	*Timestamp_Seconds
	Unit                 isTimestamp_Unit `protobuf_oneof:"unit"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Timestamp) Reset()         { *m = Timestamp{} }
func (m *Timestamp) String() string { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()    {}
func (*Timestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b183e2ab5f66472f, []int{0}
}

func (m *Timestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Timestamp.Unmarshal(m, b)
}
func (m *Timestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Timestamp.Marshal(b, m, deterministic)
}
func (m *Timestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Timestamp.Merge(m, src)
}
func (m *Timestamp) XXX_Size() int {
	return xxx_messageInfo_Timestamp.Size(m)
}
func (m *Timestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Timestamp.DiscardUnknown(m)
}

var xxx_messageInfo_Timestamp proto.InternalMessageInfo

type isTimestamp_Unit interface {
	isTimestamp_Unit()
}

type Timestamp_Nanoseconds struct {
	Nanoseconds int64 `protobuf:"varint,1,opt,name=nanoseconds,proto3,oneof"`
}

type Timestamp_Milliseconds struct {
	Milliseconds int64 `protobuf:"varint,2,opt,name=milliseconds,proto3,oneof"`
}

type Timestamp_Seconds struct {
	Seconds int64 `protobuf:"varint,3,opt,name=seconds,proto3,oneof"`
}

func (*Timestamp_Nanoseconds) isTimestamp_Unit() {}

func (*Timestamp_Milliseconds) isTimestamp_Unit() {}

func (*Timestamp_Seconds) isTimestamp_Unit() {}

func (m *Timestamp) GetUnit() isTimestamp_Unit {
	if m != nil {
		return m.Unit
	}
	return nil
}

func (m *Timestamp) GetNanoseconds() int64 {
	if x, ok := m.GetUnit().(*Timestamp_Nanoseconds); ok {
		return x.Nanoseconds
	}
	return 0
}

func (m *Timestamp) GetMilliseconds() int64 {
	if x, ok := m.GetUnit().(*Timestamp_Milliseconds); ok {
		return x.Milliseconds
	}
	return 0
}

func (m *Timestamp) GetSeconds() int64 {
	if x, ok := m.GetUnit().(*Timestamp_Seconds); ok {
		return x.Seconds
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Timestamp) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Timestamp_OneofMarshaler, _Timestamp_OneofUnmarshaler, _Timestamp_OneofSizer, []interface{}{
		(*Timestamp_Nanoseconds)(nil),
		(*Timestamp_Milliseconds)(nil),
		(*Timestamp_Seconds)(nil),
	}
}

func _Timestamp_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Timestamp)
	// unit
	switch x := m.Unit.(type) {
	case *Timestamp_Nanoseconds:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Nanoseconds))
	case *Timestamp_Milliseconds:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Milliseconds))
	case *Timestamp_Seconds:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Seconds))
	case nil:
	default:
		return fmt.Errorf("Timestamp.Unit has unexpected type %T", x)
	}
	return nil
}

func _Timestamp_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Timestamp)
	switch tag {
	case 1: // unit.nanoseconds
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Unit = &Timestamp_Nanoseconds{int64(x)}
		return true, err
	case 2: // unit.milliseconds
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Unit = &Timestamp_Milliseconds{int64(x)}
		return true, err
	case 3: // unit.seconds
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Unit = &Timestamp_Seconds{int64(x)}
		return true, err
	default:
		return false, nil
	}
}

func _Timestamp_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Timestamp)
	// unit
	switch x := m.Unit.(type) {
	case *Timestamp_Nanoseconds:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Nanoseconds))
	case *Timestamp_Milliseconds:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Milliseconds))
	case *Timestamp_Seconds:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Seconds))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Duration struct {
	// Types that are valid to be assigned to Unit:
	//	*Duration_Nanoseconds
	//	*Duration_Milliseconds
	//	*Duration_Seconds
	Unit                 isDuration_Unit `protobuf_oneof:"unit"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Duration) Reset()         { *m = Duration{} }
func (m *Duration) String() string { return proto.CompactTextString(m) }
func (*Duration) ProtoMessage()    {}
func (*Duration) Descriptor() ([]byte, []int) {
	return fileDescriptor_b183e2ab5f66472f, []int{1}
}

func (m *Duration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Duration.Unmarshal(m, b)
}
func (m *Duration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Duration.Marshal(b, m, deterministic)
}
func (m *Duration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Duration.Merge(m, src)
}
func (m *Duration) XXX_Size() int {
	return xxx_messageInfo_Duration.Size(m)
}
func (m *Duration) XXX_DiscardUnknown() {
	xxx_messageInfo_Duration.DiscardUnknown(m)
}

var xxx_messageInfo_Duration proto.InternalMessageInfo

type isDuration_Unit interface {
	isDuration_Unit()
}

type Duration_Nanoseconds struct {
	Nanoseconds int64 `protobuf:"varint,1,opt,name=nanoseconds,proto3,oneof"`
}

type Duration_Milliseconds struct {
	Milliseconds int64 `protobuf:"varint,2,opt,name=milliseconds,proto3,oneof"`
}

type Duration_Seconds struct {
	Seconds int64 `protobuf:"varint,3,opt,name=seconds,proto3,oneof"`
}

func (*Duration_Nanoseconds) isDuration_Unit() {}

func (*Duration_Milliseconds) isDuration_Unit() {}

func (*Duration_Seconds) isDuration_Unit() {}

func (m *Duration) GetUnit() isDuration_Unit {
	if m != nil {
		return m.Unit
	}
	return nil
}

func (m *Duration) GetNanoseconds() int64 {
	if x, ok := m.GetUnit().(*Duration_Nanoseconds); ok {
		return x.Nanoseconds
	}
	return 0
}

func (m *Duration) GetMilliseconds() int64 {
	if x, ok := m.GetUnit().(*Duration_Milliseconds); ok {
		return x.Milliseconds
	}
	return 0
}

func (m *Duration) GetSeconds() int64 {
	if x, ok := m.GetUnit().(*Duration_Seconds); ok {
		return x.Seconds
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Duration) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Duration_OneofMarshaler, _Duration_OneofUnmarshaler, _Duration_OneofSizer, []interface{}{
		(*Duration_Nanoseconds)(nil),
		(*Duration_Milliseconds)(nil),
		(*Duration_Seconds)(nil),
	}
}

func _Duration_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Duration)
	// unit
	switch x := m.Unit.(type) {
	case *Duration_Nanoseconds:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Nanoseconds))
	case *Duration_Milliseconds:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Milliseconds))
	case *Duration_Seconds:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Seconds))
	case nil:
	default:
		return fmt.Errorf("Duration.Unit has unexpected type %T", x)
	}
	return nil
}

func _Duration_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Duration)
	switch tag {
	case 1: // unit.nanoseconds
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Unit = &Duration_Nanoseconds{int64(x)}
		return true, err
	case 2: // unit.milliseconds
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Unit = &Duration_Milliseconds{int64(x)}
		return true, err
	case 3: // unit.seconds
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Unit = &Duration_Seconds{int64(x)}
		return true, err
	default:
		return false, nil
	}
}

func _Duration_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Duration)
	// unit
	switch x := m.Unit.(type) {
	case *Duration_Nanoseconds:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Nanoseconds))
	case *Duration_Milliseconds:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Milliseconds))
	case *Duration_Seconds:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Seconds))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Timestamp)(nil), "serving.Timestamp")
	proto.RegisterType((*Duration)(nil), "serving.Duration")
}

func init() { proto.RegisterFile("proto/time.proto", fileDescriptor_b183e2ab5f66472f) }

var fileDescriptor_b183e2ab5f66472f = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0xc9, 0xcc, 0x4d, 0xd5, 0x03, 0x33, 0x85, 0xd8, 0x8b, 0x53, 0x8b, 0xca, 0x32,
	0xf3, 0xd2, 0x95, 0x2a, 0xb9, 0x38, 0x43, 0x32, 0x73, 0x53, 0x8b, 0x4b, 0x12, 0x73, 0x0b, 0x84,
	0x94, 0xb8, 0xb8, 0xf3, 0x12, 0xf3, 0xf2, 0x8b, 0x53, 0x93, 0xf3, 0xf3, 0x52, 0x8a, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x98, 0x3d, 0x18, 0x82, 0x90, 0x05, 0x85, 0x54, 0xb8, 0x78, 0x72, 0x33, 0x73,
	0x72, 0x32, 0x61, 0x8a, 0x98, 0xa0, 0x8a, 0x50, 0x44, 0x85, 0xa4, 0xb8, 0xd8, 0x61, 0x0a, 0x98,
	0xa1, 0x0a, 0x60, 0x02, 0x4e, 0x6c, 0x5c, 0x2c, 0xa5, 0x79, 0x99, 0x25, 0x4a, 0x15, 0x5c, 0x1c,
	0x2e, 0xa5, 0x45, 0x89, 0x25, 0x99, 0xf9, 0x79, 0xf4, 0xb5, 0xd9, 0x49, 0x39, 0x4a, 0x31, 0x3d,
	0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39, 0x3f, 0x57, 0x3f, 0xb5, 0xa2, 0x20, 0x27, 0x3f, 0x25,
	0xb5, 0x58, 0x1f, 0x1a, 0x26, 0xfa, 0xe0, 0x20, 0x4a, 0x62, 0x03, 0x53, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xaa, 0x47, 0xc1, 0x12, 0x3d, 0x01, 0x00, 0x00,
}
