// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitor/monitor.proto

package monitor

import (
	fmt "fmt"
	proto1 "github.com/explodes/serving/proto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	Services             []*Config_Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_94d5950496a7550d, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetServices() []*Config_Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Config_Service struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              *proto1.Address  `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	UpdateFrequency      *proto1.Duration `protobuf:"bytes,3,opt,name=update_frequency,json=updateFrequency,proto3" json:"update_frequency,omitempty"`
	Timeout              *proto1.Duration `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Config_Service) Reset()         { *m = Config_Service{} }
func (m *Config_Service) String() string { return proto.CompactTextString(m) }
func (*Config_Service) ProtoMessage()    {}
func (*Config_Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_94d5950496a7550d, []int{0, 0}
}

func (m *Config_Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config_Service.Unmarshal(m, b)
}
func (m *Config_Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config_Service.Marshal(b, m, deterministic)
}
func (m *Config_Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config_Service.Merge(m, src)
}
func (m *Config_Service) XXX_Size() int {
	return xxx_messageInfo_Config_Service.Size(m)
}
func (m *Config_Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Config_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Config_Service proto.InternalMessageInfo

func (m *Config_Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Config_Service) GetAddress() *proto1.Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Config_Service) GetUpdateFrequency() *proto1.Duration {
	if m != nil {
		return m.UpdateFrequency
	}
	return nil
}

func (m *Config_Service) GetTimeout() *proto1.Duration {
	if m != nil {
		return m.Timeout
	}
	return nil
}

func init() {
	proto.RegisterType((*Config)(nil), "monitor.Config")
	proto.RegisterType((*Config_Service)(nil), "monitor.Config.Service")
}

func init() { proto.RegisterFile("monitor/monitor.proto", fileDescriptor_94d5950496a7550d) }

var fileDescriptor_94d5950496a7550d = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0xc7, 0x89, 0xbb, 0x6c, 0x35, 0x7b, 0xb0, 0x46, 0xc4, 0xd0, 0x53, 0x51, 0x84, 0xa2, 0x90,
	0xc2, 0xee, 0xd5, 0x8b, 0x1f, 0xf8, 0x00, 0xf5, 0xe6, 0x45, 0xba, 0xed, 0x6c, 0x0d, 0xd8, 0x4c,
	0xcd, 0x87, 0xe8, 0x7b, 0xf9, 0x68, 0x3e, 0x80, 0x98, 0x8f, 0xbd, 0xed, 0x29, 0x99, 0xff, 0xfc,
	0x7e, 0x21, 0x33, 0xf4, 0x6c, 0x44, 0x25, 0x2d, 0xea, 0x3a, 0x9e, 0x62, 0xd2, 0x68, 0x91, 0x65,
	0xb1, 0x2c, 0x4e, 0x7d, 0x5d, 0xb7, 0x7d, 0xaf, 0xc1, 0x98, 0xd0, 0x2d, 0xf2, 0x10, 0x5a, 0x39,
	0x42, 0x48, 0x2e, 0x7e, 0x09, 0x5d, 0x3c, 0xa0, 0xda, 0xca, 0x81, 0xad, 0xe9, 0xa1, 0x01, 0xfd,
	0x29, 0x3b, 0x30, 0x9c, 0x94, 0xb3, 0x6a, 0xb9, 0x3a, 0x17, 0xe9, 0xf1, 0x80, 0x88, 0xe7, 0xd0,
	0x6f, 0x76, 0x60, 0xf1, 0x43, 0x68, 0x16, 0x53, 0xc6, 0xe8, 0x5c, 0xb5, 0x23, 0x70, 0x52, 0x92,
	0xea, 0xa8, 0xf1, 0x77, 0x76, 0x4d, 0xb3, 0xf8, 0x05, 0x7e, 0x50, 0x92, 0x6a, 0xb9, 0xca, 0x85,
	0x77, 0xd5, 0x20, 0xee, 0x42, 0xde, 0x24, 0x80, 0xdd, 0xd2, 0xdc, 0x4d, 0x7d, 0x6b, 0xe1, 0x75,
	0xab, 0xe1, 0xc3, 0x81, 0xea, 0xbe, 0xf9, 0xcc, 0x4b, 0x27, 0x3b, 0xe9, 0xd1, 0xe9, 0xd6, 0x4a,
	0x54, 0xcd, 0x71, 0x40, 0x9f, 0x12, 0xc9, 0x6e, 0x68, 0xf6, 0x3f, 0x17, 0x3a, 0xcb, 0xe7, 0xfb,
	0xa4, 0x44, 0xdc, 0x5f, 0xbd, 0x5c, 0x0e, 0xd2, 0xbe, 0xb9, 0x8d, 0xe8, 0x70, 0xac, 0xe1, 0x6b,
	0x7a, 0xc7, 0x1e, 0x4c, 0x1d, 0x85, 0xb4, 0xd3, 0xcd, 0xc2, 0x2f, 0x69, 0xfd, 0x17, 0x00, 0x00,
	0xff, 0xff, 0x44, 0x66, 0x06, 0x58, 0x6d, 0x01, 0x00, 0x00,
}
