bind_address {
  host: "0.0.0.0"
  port: 4004
}
json_bind_address {
 host: "0.0.0.0"
 port: 7004
}
logz_server {
  address {
    host: "0.0.0.0"
    port: 4001
  }
  enable_gzip: true
  exponential_backoff {
  }
}
expz_server {
  address {
    host: "0.0.0.0"
    port: 4002
  }
  enable_gzip: true
  exponential_backoff {
  }
}
database_address {
  postgres {
    url: "postgresql://userz:userzpass@localhost:5433/userz"
  }
}
cookie_passcode: "tacoboats99999lmao"
cookie_salt: "boatsoftacos344444rofl"