// Code generated by protoc-gen-go. DO NOT EDIT.
// source: expz/service.proto

package expz

import (
	fmt "fmt"
	proto1 "github.com/explodes/serving/proto"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExpzConfig struct {
	BindAddress          *proto1.Address                    `protobuf:"bytes,1,opt,name=bind_address,json=bindAddress,proto3" json:"bind_address,omitempty"`
	LogzAddress          *proto1.Address                    `protobuf:"bytes,2,opt,name=logz_address,json=logzAddress,proto3" json:"logz_address,omitempty"`
	DefaultFeatures      []*FeatureDeclaration              `protobuf:"bytes,3,rep,name=default_features,json=defaultFeatures,proto3" json:"default_features,omitempty"`
	ExperimentalFeatures []*ExpzConfig_ExperimentalFeatures `protobuf:"bytes,4,rep,name=experimental_features,json=experimentalFeatures,proto3" json:"experimental_features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *ExpzConfig) Reset()         { *m = ExpzConfig{} }
func (m *ExpzConfig) String() string { return proto.CompactTextString(m) }
func (*ExpzConfig) ProtoMessage()    {}
func (*ExpzConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfab7f94f2819cc9, []int{0}
}

func (m *ExpzConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpzConfig.Unmarshal(m, b)
}
func (m *ExpzConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpzConfig.Marshal(b, m, deterministic)
}
func (m *ExpzConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpzConfig.Merge(m, src)
}
func (m *ExpzConfig) XXX_Size() int {
	return xxx_messageInfo_ExpzConfig.Size(m)
}
func (m *ExpzConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpzConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ExpzConfig proto.InternalMessageInfo

func (m *ExpzConfig) GetBindAddress() *proto1.Address {
	if m != nil {
		return m.BindAddress
	}
	return nil
}

func (m *ExpzConfig) GetLogzAddress() *proto1.Address {
	if m != nil {
		return m.LogzAddress
	}
	return nil
}

func (m *ExpzConfig) GetDefaultFeatures() []*FeatureDeclaration {
	if m != nil {
		return m.DefaultFeatures
	}
	return nil
}

func (m *ExpzConfig) GetExperimentalFeatures() []*ExpzConfig_ExperimentalFeatures {
	if m != nil {
		return m.ExperimentalFeatures
	}
	return nil
}

type ExpzConfig_ExperimentalFeatures struct {
	Name                 string                                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Doc                  string                                `protobuf:"bytes,2,opt,name=doc,proto3" json:"doc,omitempty"`
	Mods                 *ExpzConfig_ExperimentalFeatures_Mods `protobuf:"bytes,3,opt,name=mods,proto3" json:"mods,omitempty"`
	Features             *Features                             `protobuf:"bytes,4,opt,name=features,proto3" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ExpzConfig_ExperimentalFeatures) Reset()         { *m = ExpzConfig_ExperimentalFeatures{} }
func (m *ExpzConfig_ExperimentalFeatures) String() string { return proto.CompactTextString(m) }
func (*ExpzConfig_ExperimentalFeatures) ProtoMessage()    {}
func (*ExpzConfig_ExperimentalFeatures) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfab7f94f2819cc9, []int{0, 0}
}

func (m *ExpzConfig_ExperimentalFeatures) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpzConfig_ExperimentalFeatures.Unmarshal(m, b)
}
func (m *ExpzConfig_ExperimentalFeatures) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpzConfig_ExperimentalFeatures.Marshal(b, m, deterministic)
}
func (m *ExpzConfig_ExperimentalFeatures) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpzConfig_ExperimentalFeatures.Merge(m, src)
}
func (m *ExpzConfig_ExperimentalFeatures) XXX_Size() int {
	return xxx_messageInfo_ExpzConfig_ExperimentalFeatures.Size(m)
}
func (m *ExpzConfig_ExperimentalFeatures) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpzConfig_ExperimentalFeatures.DiscardUnknown(m)
}

var xxx_messageInfo_ExpzConfig_ExperimentalFeatures proto.InternalMessageInfo

func (m *ExpzConfig_ExperimentalFeatures) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExpzConfig_ExperimentalFeatures) GetDoc() string {
	if m != nil {
		return m.Doc
	}
	return ""
}

func (m *ExpzConfig_ExperimentalFeatures) GetMods() *ExpzConfig_ExperimentalFeatures_Mods {
	if m != nil {
		return m.Mods
	}
	return nil
}

func (m *ExpzConfig_ExperimentalFeatures) GetFeatures() *Features {
	if m != nil {
		return m.Features
	}
	return nil
}

// A range within [0, 999] representing which mods should receive the feature set.
type ExpzConfig_ExperimentalFeatures_Mods struct {
	Min                  uint32   `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max                  uint32   `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExpzConfig_ExperimentalFeatures_Mods) Reset()         { *m = ExpzConfig_ExperimentalFeatures_Mods{} }
func (m *ExpzConfig_ExperimentalFeatures_Mods) String() string { return proto.CompactTextString(m) }
func (*ExpzConfig_ExperimentalFeatures_Mods) ProtoMessage()    {}
func (*ExpzConfig_ExperimentalFeatures_Mods) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfab7f94f2819cc9, []int{0, 0, 0}
}

func (m *ExpzConfig_ExperimentalFeatures_Mods) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpzConfig_ExperimentalFeatures_Mods.Unmarshal(m, b)
}
func (m *ExpzConfig_ExperimentalFeatures_Mods) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpzConfig_ExperimentalFeatures_Mods.Marshal(b, m, deterministic)
}
func (m *ExpzConfig_ExperimentalFeatures_Mods) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpzConfig_ExperimentalFeatures_Mods.Merge(m, src)
}
func (m *ExpzConfig_ExperimentalFeatures_Mods) XXX_Size() int {
	return xxx_messageInfo_ExpzConfig_ExperimentalFeatures_Mods.Size(m)
}
func (m *ExpzConfig_ExperimentalFeatures_Mods) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpzConfig_ExperimentalFeatures_Mods.DiscardUnknown(m)
}

var xxx_messageInfo_ExpzConfig_ExperimentalFeatures_Mods proto.InternalMessageInfo

func (m *ExpzConfig_ExperimentalFeatures_Mods) GetMin() uint32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *ExpzConfig_ExperimentalFeatures_Mods) GetMax() uint32 {
	if m != nil {
		return m.Max
	}
	return 0
}

type GetExperimentsRequest struct {
	Cookie               string   `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetExperimentsRequest) Reset()         { *m = GetExperimentsRequest{} }
func (m *GetExperimentsRequest) String() string { return proto.CompactTextString(m) }
func (*GetExperimentsRequest) ProtoMessage()    {}
func (*GetExperimentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfab7f94f2819cc9, []int{1}
}

func (m *GetExperimentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExperimentsRequest.Unmarshal(m, b)
}
func (m *GetExperimentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExperimentsRequest.Marshal(b, m, deterministic)
}
func (m *GetExperimentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExperimentsRequest.Merge(m, src)
}
func (m *GetExperimentsRequest) XXX_Size() int {
	return xxx_messageInfo_GetExperimentsRequest.Size(m)
}
func (m *GetExperimentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExperimentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetExperimentsRequest proto.InternalMessageInfo

func (m *GetExperimentsRequest) GetCookie() string {
	if m != nil {
		return m.Cookie
	}
	return ""
}

type GetExperimentsResponse struct {
	Features             *Features `protobuf:"bytes,1,opt,name=features,proto3" json:"features,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetExperimentsResponse) Reset()         { *m = GetExperimentsResponse{} }
func (m *GetExperimentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetExperimentsResponse) ProtoMessage()    {}
func (*GetExperimentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfab7f94f2819cc9, []int{2}
}

func (m *GetExperimentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetExperimentsResponse.Unmarshal(m, b)
}
func (m *GetExperimentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetExperimentsResponse.Marshal(b, m, deterministic)
}
func (m *GetExperimentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetExperimentsResponse.Merge(m, src)
}
func (m *GetExperimentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetExperimentsResponse.Size(m)
}
func (m *GetExperimentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetExperimentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetExperimentsResponse proto.InternalMessageInfo

func (m *GetExperimentsResponse) GetFeatures() *Features {
	if m != nil {
		return m.Features
	}
	return nil
}

func init() {
	proto.RegisterType((*ExpzConfig)(nil), "expz.ExpzConfig")
	proto.RegisterType((*ExpzConfig_ExperimentalFeatures)(nil), "expz.ExpzConfig.ExperimentalFeatures")
	proto.RegisterType((*ExpzConfig_ExperimentalFeatures_Mods)(nil), "expz.ExpzConfig.ExperimentalFeatures.Mods")
	proto.RegisterType((*GetExperimentsRequest)(nil), "expz.GetExperimentsRequest")
	proto.RegisterType((*GetExperimentsResponse)(nil), "expz.GetExperimentsResponse")
}

func init() { proto.RegisterFile("expz/service.proto", fileDescriptor_bfab7f94f2819cc9) }

var fileDescriptor_bfab7f94f2819cc9 = []byte{
	// 436 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x25, 0xc4, 0xaa, 0xe8, 0x04, 0x9a, 0x68, 0xdb, 0xa2, 0x60, 0x38, 0x44, 0x96, 0x90, 0xaa,
	0x20, 0x39, 0x52, 0x7a, 0x47, 0xa2, 0x09, 0x70, 0xea, 0x65, 0xb9, 0x55, 0x48, 0xd5, 0xc6, 0x9e,
	0x84, 0x15, 0xb6, 0xd7, 0x78, 0x37, 0xc8, 0xca, 0x91, 0x7f, 0xe2, 0x4f, 0xf8, 0x0e, 0xbe, 0x01,
	0xcd, 0xec, 0x26, 0x21, 0x28, 0x20, 0x2e, 0xc9, 0xf8, 0xcd, 0xbc, 0xb7, 0xef, 0x8d, 0xbd, 0x20,
	0xb0, 0xad, 0x37, 0x13, 0x8b, 0xcd, 0x57, 0x9d, 0x61, 0x5a, 0x37, 0xc6, 0x19, 0x11, 0x11, 0x16,
	0xf7, 0xb9, 0x43, 0x3f, 0x1e, 0x8e, 0xcf, 0xf9, 0x6f, 0xa2, 0xf2, 0xbc, 0x41, 0x6b, 0x03, 0xf8,
	0xcc, 0x83, 0x16, 0x1b, 0xad, 0x0a, 0xbd, 0x51, 0x4e, 0x9b, 0xca, 0xb7, 0x92, 0x9f, 0x5d, 0x80,
	0xb7, 0x6d, 0xbd, 0x99, 0x99, 0x6a, 0xa9, 0x57, 0xe2, 0x1a, 0x1e, 0x2f, 0x74, 0x95, 0xdf, 0x07,
	0xfe, 0xb0, 0x33, 0xea, 0x5c, 0xf5, 0xa6, 0x83, 0x94, 0xcf, 0xae, 0x56, 0xe9, 0x1b, 0x8f, 0xcb,
	0x1e, 0x4d, 0x85, 0x07, 0x22, 0x15, 0x66, 0xb5, 0xd9, 0x91, 0x1e, 0xfe, 0x8d, 0x44, 0x53, 0x5b,
	0xd2, 0x0c, 0x06, 0x39, 0x2e, 0xd5, 0xba, 0x70, 0xf7, 0x4b, 0x54, 0x6e, 0xdd, 0xa0, 0x1d, 0x76,
	0x47, 0xdd, 0xab, 0xde, 0x74, 0x98, 0x72, 0x9e, 0x77, 0x1e, 0x9d, 0x63, 0x56, 0xa8, 0x86, 0x2d,
	0xcb, 0x7e, 0x60, 0x84, 0x96, 0x15, 0x77, 0x70, 0x89, 0x6d, 0x8d, 0x8d, 0x2e, 0xb1, 0x72, 0xaa,
	0xd8, 0x2b, 0x45, 0xac, 0xf4, 0xd2, 0x2b, 0xed, 0xf3, 0x51, 0xb9, 0x9b, 0xde, 0xaa, 0xc8, 0x0b,
	0x3c, 0x82, 0xc6, 0x3f, 0x3a, 0x70, 0x71, 0x6c, 0x5c, 0x08, 0x88, 0x2a, 0x55, 0x22, 0xef, 0xe6,
	0x54, 0x72, 0x2d, 0x06, 0xd0, 0xcd, 0x4d, 0xc6, 0xc9, 0x4f, 0x25, 0x95, 0xe2, 0x35, 0x44, 0xa5,
	0xc9, 0x29, 0x13, 0x2d, 0x63, 0xfc, 0x5f, 0x4e, 0xd2, 0x5b, 0x93, 0x5b, 0xc9, 0x3c, 0x31, 0x86,
	0x47, 0xbf, 0xa5, 0x21, 0x8d, 0xb3, 0x83, 0xbd, 0x58, 0xb9, 0xeb, 0xc7, 0x63, 0x88, 0x88, 0x49,
	0x2e, 0x4a, 0x5d, 0xb1, 0xb1, 0x27, 0x92, 0x4a, 0x46, 0x54, 0xcb, 0xbe, 0x08, 0x51, 0x6d, 0x32,
	0x87, 0xcb, 0xf7, 0xe8, 0xf6, 0xa7, 0x5b, 0x89, 0x5f, 0xd6, 0x68, 0x9d, 0x78, 0x05, 0x27, 0x99,
	0x31, 0x9f, 0x75, 0x08, 0x76, 0x73, 0xfe, 0xed, 0xfb, 0xb0, 0xbf, 0x7b, 0x87, 0x33, 0x6e, 0xc9,
	0x30, 0x92, 0xcc, 0xe1, 0xe9, 0x9f, 0x2a, 0xb6, 0x36, 0x95, 0xc5, 0x03, 0xdf, 0x9d, 0x7f, 0xfb,
	0x9e, 0x7e, 0x84, 0x1e, 0x6d, 0xe4, 0x83, 0xff, 0xb0, 0xc5, 0x2d, 0x9c, 0x1d, 0x8a, 0x8a, 0xe7,
	0x9e, 0x7a, 0xd4, 0x70, 0xfc, 0xe2, 0x78, 0xd3, 0xfb, 0x48, 0x1e, 0xdc, 0x24, 0x77, 0xa3, 0x95,
	0x76, 0x9f, 0xd6, 0x8b, 0x34, 0x33, 0x25, 0xdd, 0x91, 0xc2, 0xe4, 0x68, 0x27, 0x21, 0x11, 0x5f,
	0x9a, 0xc5, 0x09, 0xdf, 0x82, 0xeb, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x78, 0xa7, 0x34, 0x29,
	0x62, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExpzServiceClient is the client API for ExpzService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExpzServiceClient interface {
	GetExperiments(ctx context.Context, in *GetExperimentsRequest, opts ...grpc.CallOption) (*GetExperimentsResponse, error)
}

type expzServiceClient struct {
	cc *grpc.ClientConn
}

func NewExpzServiceClient(cc *grpc.ClientConn) ExpzServiceClient {
	return &expzServiceClient{cc}
}

func (c *expzServiceClient) GetExperiments(ctx context.Context, in *GetExperimentsRequest, opts ...grpc.CallOption) (*GetExperimentsResponse, error) {
	out := new(GetExperimentsResponse)
	err := c.cc.Invoke(ctx, "/expz.ExpzService/GetExperiments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExpzServiceServer is the server API for ExpzService service.
type ExpzServiceServer interface {
	GetExperiments(context.Context, *GetExperimentsRequest) (*GetExperimentsResponse, error)
}

func RegisterExpzServiceServer(s *grpc.Server, srv ExpzServiceServer) {
	s.RegisterService(&_ExpzService_serviceDesc, srv)
}

func _ExpzService_GetExperiments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExperimentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExpzServiceServer).GetExperiments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/expz.ExpzService/GetExperiments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExpzServiceServer).GetExperiments(ctx, req.(*GetExperimentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExpzService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "expz.ExpzService",
	HandlerType: (*ExpzServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExperiments",
			Handler:    _ExpzService_GetExperiments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "expz/service.proto",
}
