// Code generated by protoc-gen-go. DO NOT EDIT.
// source: statusz/service.proto

package statusz

import (
	fmt "fmt"
	_ "github.com/explodes/serving/proto"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetStatusRequest struct {
	Cookie               string   `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusRequest) Reset()         { *m = GetStatusRequest{} }
func (m *GetStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetStatusRequest) ProtoMessage()    {}
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e160ec42757835ac, []int{0}
}

func (m *GetStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusRequest.Unmarshal(m, b)
}
func (m *GetStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusRequest.Merge(m, src)
}
func (m *GetStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetStatusRequest.Size(m)
}
func (m *GetStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusRequest proto.InternalMessageInfo

func (m *GetStatusRequest) GetCookie() string {
	if m != nil {
		return m.Cookie
	}
	return ""
}

type GetStatusResponse struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStatusResponse) Reset()         { *m = GetStatusResponse{} }
func (m *GetStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetStatusResponse) ProtoMessage()    {}
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e160ec42757835ac, []int{1}
}

func (m *GetStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStatusResponse.Unmarshal(m, b)
}
func (m *GetStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStatusResponse.Merge(m, src)
}
func (m *GetStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetStatusResponse.Size(m)
}
func (m *GetStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStatusResponse proto.InternalMessageInfo

func (m *GetStatusResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*GetStatusRequest)(nil), "statusz.GetStatusRequest")
	proto.RegisterType((*GetStatusResponse)(nil), "statusz.GetStatusResponse")
}

func init() { proto.RegisterFile("statusz/service.proto", fileDescriptor_e160ec42757835ac) }

var fileDescriptor_e160ec42757835ac = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x2e, 0x49, 0x2c,
	0x29, 0x2d, 0xae, 0xd2, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x62, 0x87, 0x0a, 0x4b, 0x21, 0xe4, 0x21, 0x34, 0x44, 0x5e, 0x4a, 0x12, 0x4c, 0x81,
	0x34, 0x65, 0x26, 0xe6, 0x64, 0x56, 0x25, 0x96, 0x64, 0xe6, 0xe7, 0x41, 0xa4, 0x94, 0xec, 0xb9,
	0x04, 0xdc, 0x53, 0x4b, 0x82, 0xc1, 0xca, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xb4,
	0xb9, 0xd8, 0x92, 0xf3, 0xf3, 0xb3, 0x33, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x9d, 0x84,
	0x9b, 0xb6, 0x4a, 0xf0, 0xeb, 0x81, 0xad, 0xcc, 0x4b, 0xd7, 0x73, 0x06, 0x4b, 0x05, 0x41, 0x95,
	0x28, 0xd9, 0x70, 0x09, 0x22, 0x19, 0x50, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0xa4, 0xce, 0xc5,
	0x06, 0x71, 0x01, 0xd8, 0x04, 0x6e, 0x23, 0x7e, 0x3d, 0x98, 0x83, 0xa0, 0x0a, 0xa1, 0xd2, 0x46,
	0x61, 0x5c, 0x7c, 0x10, 0x91, 0xaa, 0x60, 0x88, 0x8f, 0x84, 0x5c, 0xb8, 0x38, 0xe1, 0xe6, 0x09,
	0x49, 0xc2, 0xf5, 0xa1, 0x3b, 0x52, 0x4a, 0x0a, 0x9b, 0x14, 0xc4, 0x7a, 0x25, 0x06, 0x27, 0xd5,
	0x28, 0xe5, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0xd4, 0x8a, 0x82,
	0x9c, 0xfc, 0x94, 0xd4, 0x62, 0x7d, 0xa8, 0x1f, 0x60, 0xc1, 0x93, 0xc4, 0x06, 0x0e, 0x04, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x8c, 0x3e, 0xfc, 0x58, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatuszServiceClient is the client API for StatuszService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatuszServiceClient interface {
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
}

type statuszServiceClient struct {
	cc *grpc.ClientConn
}

func NewStatuszServiceClient(cc *grpc.ClientConn) StatuszServiceClient {
	return &statuszServiceClient{cc}
}

func (c *statuszServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, "/statusz.StatuszService/GetStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatuszServiceServer is the server API for StatuszService service.
type StatuszServiceServer interface {
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
}

func RegisterStatuszServiceServer(s *grpc.Server, srv StatuszServiceServer) {
	s.RegisterService(&_StatuszService_serviceDesc, srv)
}

func _StatuszService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatuszServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/statusz.StatuszService/GetStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatuszServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StatuszService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "statusz.StatuszService",
	HandlerType: (*StatuszServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _StatuszService_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "statusz/service.proto",
}
