// Code generated by protoc-gen-go. DO NOT EDIT.
// source: statusz/statusz.proto

package statusz

import (
	fmt "fmt"
	proto1 "github.com/explodes/serving/proto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status struct {
	Timestamp            *proto1.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Groups               []*MetricGroup    `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_268982af76b02c46, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetTimestamp() *proto1.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Status) GetGroups() []*MetricGroup {
	if m != nil {
		return m.Groups
	}
	return nil
}

type MetricGroup struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Metrics              []*Metric `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MetricGroup) Reset()         { *m = MetricGroup{} }
func (m *MetricGroup) String() string { return proto.CompactTextString(m) }
func (*MetricGroup) ProtoMessage()    {}
func (*MetricGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_268982af76b02c46, []int{1}
}

func (m *MetricGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricGroup.Unmarshal(m, b)
}
func (m *MetricGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricGroup.Marshal(b, m, deterministic)
}
func (m *MetricGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricGroup.Merge(m, src)
}
func (m *MetricGroup) XXX_Size() int {
	return xxx_messageInfo_MetricGroup.Size(m)
}
func (m *MetricGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricGroup.DiscardUnknown(m)
}

var xxx_messageInfo_MetricGroup proto.InternalMessageInfo

func (m *MetricGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetricGroup) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type Metric struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Metric_I64
	//	*Metric_U64
	//	*Metric_F64
	//	*Metric_String_
	//	*Metric_Bool
	//	*Metric_Duration
	Value                isMetric_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_268982af76b02c46, []int{2}
}

func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type isMetric_Value interface {
	isMetric_Value()
}

type Metric_I64 struct {
	I64 int64 `protobuf:"varint,2,opt,name=i64,proto3,oneof"`
}

type Metric_U64 struct {
	U64 uint64 `protobuf:"varint,3,opt,name=u64,proto3,oneof"`
}

type Metric_F64 struct {
	F64 float64 `protobuf:"fixed64,4,opt,name=f64,proto3,oneof"`
}

type Metric_String_ struct {
	String_ string `protobuf:"bytes,5,opt,name=string,proto3,oneof"`
}

type Metric_Bool struct {
	Bool bool `protobuf:"varint,6,opt,name=bool,proto3,oneof"`
}

type Metric_Duration struct {
	Duration *proto1.Duration `protobuf:"bytes,7,opt,name=duration,proto3,oneof"`
}

func (*Metric_I64) isMetric_Value() {}

func (*Metric_U64) isMetric_Value() {}

func (*Metric_F64) isMetric_Value() {}

func (*Metric_String_) isMetric_Value() {}

func (*Metric_Bool) isMetric_Value() {}

func (*Metric_Duration) isMetric_Value() {}

func (m *Metric) GetValue() isMetric_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Metric) GetI64() int64 {
	if x, ok := m.GetValue().(*Metric_I64); ok {
		return x.I64
	}
	return 0
}

func (m *Metric) GetU64() uint64 {
	if x, ok := m.GetValue().(*Metric_U64); ok {
		return x.U64
	}
	return 0
}

func (m *Metric) GetF64() float64 {
	if x, ok := m.GetValue().(*Metric_F64); ok {
		return x.F64
	}
	return 0
}

func (m *Metric) GetString_() string {
	if x, ok := m.GetValue().(*Metric_String_); ok {
		return x.String_
	}
	return ""
}

func (m *Metric) GetBool() bool {
	if x, ok := m.GetValue().(*Metric_Bool); ok {
		return x.Bool
	}
	return false
}

func (m *Metric) GetDuration() *proto1.Duration {
	if x, ok := m.GetValue().(*Metric_Duration); ok {
		return x.Duration
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Metric) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Metric_OneofMarshaler, _Metric_OneofUnmarshaler, _Metric_OneofSizer, []interface{}{
		(*Metric_I64)(nil),
		(*Metric_U64)(nil),
		(*Metric_F64)(nil),
		(*Metric_String_)(nil),
		(*Metric_Bool)(nil),
		(*Metric_Duration)(nil),
	}
}

func _Metric_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Metric)
	// value
	switch x := m.Value.(type) {
	case *Metric_I64:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.I64))
	case *Metric_U64:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.U64))
	case *Metric_F64:
		b.EncodeVarint(4<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.F64))
	case *Metric_String_:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.String_)
	case *Metric_Bool:
		t := uint64(0)
		if x.Bool {
			t = 1
		}
		b.EncodeVarint(6<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *Metric_Duration:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Duration); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Metric.Value has unexpected type %T", x)
	}
	return nil
}

func _Metric_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Metric)
	switch tag {
	case 2: // value.i64
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Metric_I64{int64(x)}
		return true, err
	case 3: // value.u64
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Metric_U64{x}
		return true, err
	case 4: // value.f64
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.Value = &Metric_F64{math.Float64frombits(x)}
		return true, err
	case 5: // value.string
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Metric_String_{x}
		return true, err
	case 6: // value.bool
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Metric_Bool{x != 0}
		return true, err
	case 7: // value.duration
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(proto1.Duration)
		err := b.DecodeMessage(msg)
		m.Value = &Metric_Duration{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Metric_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Metric)
	// value
	switch x := m.Value.(type) {
	case *Metric_I64:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.I64))
	case *Metric_U64:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.U64))
	case *Metric_F64:
		n += 1 // tag and wire
		n += 8
	case *Metric_String_:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.String_)))
		n += len(x.String_)
	case *Metric_Bool:
		n += 1 // tag and wire
		n += 1
	case *Metric_Duration:
		s := proto.Size(x.Duration)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Status)(nil), "statusz.Status")
	proto.RegisterType((*MetricGroup)(nil), "statusz.MetricGroup")
	proto.RegisterType((*Metric)(nil), "statusz.Metric")
}

func init() { proto.RegisterFile("statusz/statusz.proto", fileDescriptor_268982af76b02c46) }

var fileDescriptor_268982af76b02c46 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0x9b, 0xb5, 0x6b, 0xb7, 0xbb, 0x07, 0x35, 0x4c, 0x08, 0x3e, 0x95, 0x89, 0x50, 0x41,
	0x5a, 0x99, 0xa5, 0x3f, 0x60, 0x08, 0xf6, 0x41, 0x5f, 0xa2, 0x4f, 0xbe, 0x75, 0x5b, 0xd6, 0x05,
	0xd6, 0xa6, 0x34, 0xc9, 0x10, 0x7f, 0x9e, 0xbf, 0x4c, 0x92, 0xb6, 0x53, 0xc4, 0xa7, 0xf6, 0x7c,
	0xe7, 0xe4, 0x5c, 0xb8, 0x17, 0x2e, 0xa5, 0x2a, 0x94, 0x96, 0x9f, 0x49, 0xff, 0x8d, 0x9b, 0x56,
	0x28, 0x81, 0x83, 0x5e, 0x5e, 0x9d, 0x5b, 0x9d, 0x28, 0x5e, 0xb1, 0xce, 0x5a, 0xec, 0xc1, 0x7f,
	0xb5, 0x26, 0xbe, 0x87, 0xa9, 0xe1, 0x52, 0x15, 0x55, 0x43, 0x50, 0x88, 0xa2, 0xd9, 0x12, 0xc7,
	0x92, 0xb5, 0x47, 0x5e, 0x97, 0xf1, 0xdb, 0xe0, 0xd0, 0x9f, 0x10, 0xbe, 0x03, 0xbf, 0x6c, 0x85,
	0x6e, 0x24, 0x19, 0x85, 0x6e, 0x34, 0x5b, 0xce, 0xe3, 0x61, 0xec, 0x0b, 0x53, 0x2d, 0xdf, 0x3c,
	0x19, 0x93, 0xf6, 0x99, 0xc5, 0x33, 0xcc, 0x7e, 0x61, 0x8c, 0xc1, 0xab, 0x8b, 0x8a, 0xd9, 0x49,
	0x53, 0x6a, 0xff, 0xf1, 0x2d, 0x04, 0x95, 0x8d, 0x48, 0xe2, 0xda, 0xc6, 0xb3, 0x3f, 0x8d, 0x74,
	0xf0, 0x17, 0x5f, 0x08, 0xfc, 0x8e, 0xfd, 0xdb, 0x84, 0xc1, 0xe5, 0x59, 0x4a, 0x46, 0x21, 0x8a,
	0xdc, 0xdc, 0xa1, 0x46, 0x18, 0xa6, 0xb3, 0x94, 0xb8, 0x21, 0x8a, 0x3c, 0xc3, 0x74, 0xc7, 0x76,
	0x59, 0x4a, 0xbc, 0x10, 0x45, 0xc8, 0xb0, 0x5d, 0x96, 0x62, 0x02, 0xbe, 0x54, 0x2d, 0xaf, 0x4b,
	0x32, 0x36, 0x8d, 0xb9, 0x43, 0x7b, 0x8d, 0xe7, 0xe0, 0xad, 0x85, 0x38, 0x10, 0x3f, 0x44, 0xd1,
	0x24, 0x77, 0xa8, 0x55, 0x38, 0x81, 0xc9, 0x56, 0xb7, 0x85, 0xe2, 0xa2, 0x26, 0x81, 0xdd, 0xdb,
	0xc5, 0x69, 0x6f, 0x8f, 0xbd, 0x91, 0x3b, 0xf4, 0x14, 0x5a, 0x05, 0x30, 0x3e, 0x16, 0x07, 0xcd,
	0x56, 0x37, 0xef, 0xd7, 0x25, 0x57, 0x7b, 0xbd, 0x8e, 0x37, 0xa2, 0x4a, 0xd8, 0x47, 0x73, 0x10,
	0x5b, 0x26, 0x93, 0xfe, 0xf1, 0x70, 0xc4, 0xb5, 0x6f, 0x4f, 0xf5, 0xf0, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0xfd, 0xe9, 0x75, 0x51, 0xde, 0x01, 0x00, 0x00,
}
