// Code generated by protoc-gen-go. DO NOT EDIT.
// source: addz/service.proto

package addz

import (
	fmt "fmt"
	proto1 "github.com/explodes/serving/proto"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddzConfig struct {
	BindAddress          *proto1.Address `protobuf:"bytes,1,opt,name=bind_address,json=bindAddress,proto3" json:"bind_address,omitempty"`
	JsonBindAddress      *proto1.Address `protobuf:"bytes,2,opt,name=json_bind_address,json=jsonBindAddress,proto3" json:"json_bind_address,omitempty"`
	LogzAddress          *proto1.Address `protobuf:"bytes,3,opt,name=logz_address,json=logzAddress,proto3" json:"logz_address,omitempty"`
	ExpzAddress          *proto1.Address `protobuf:"bytes,4,opt,name=expz_address,json=expzAddress,proto3" json:"expz_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AddzConfig) Reset()         { *m = AddzConfig{} }
func (m *AddzConfig) String() string { return proto.CompactTextString(m) }
func (*AddzConfig) ProtoMessage()    {}
func (*AddzConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fc09a9db99872d4, []int{0}
}

func (m *AddzConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddzConfig.Unmarshal(m, b)
}
func (m *AddzConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddzConfig.Marshal(b, m, deterministic)
}
func (m *AddzConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddzConfig.Merge(m, src)
}
func (m *AddzConfig) XXX_Size() int {
	return xxx_messageInfo_AddzConfig.Size(m)
}
func (m *AddzConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_AddzConfig.DiscardUnknown(m)
}

var xxx_messageInfo_AddzConfig proto.InternalMessageInfo

func (m *AddzConfig) GetBindAddress() *proto1.Address {
	if m != nil {
		return m.BindAddress
	}
	return nil
}

func (m *AddzConfig) GetJsonBindAddress() *proto1.Address {
	if m != nil {
		return m.JsonBindAddress
	}
	return nil
}

func (m *AddzConfig) GetLogzAddress() *proto1.Address {
	if m != nil {
		return m.LogzAddress
	}
	return nil
}

func (m *AddzConfig) GetExpzAddress() *proto1.Address {
	if m != nil {
		return m.ExpzAddress
	}
	return nil
}

type AddRequest struct {
	Cookie               int64    `protobuf:"varint,1,opt,name=cookie,proto3" json:"cookie,omitempty"`
	Values               []int64  `protobuf:"varint,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fc09a9db99872d4, []int{1}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetCookie() int64 {
	if m != nil {
		return m.Cookie
	}
	return 0
}

func (m *AddRequest) GetValues() []int64 {
	if m != nil {
		return m.Values
	}
	return nil
}

type AddResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fc09a9db99872d4, []int{2}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type SubtractRequest struct {
	Cookie               int64    `protobuf:"varint,1,opt,name=cookie,proto3" json:"cookie,omitempty"`
	Values               []int64  `protobuf:"varint,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubtractRequest) Reset()         { *m = SubtractRequest{} }
func (m *SubtractRequest) String() string { return proto.CompactTextString(m) }
func (*SubtractRequest) ProtoMessage()    {}
func (*SubtractRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fc09a9db99872d4, []int{3}
}

func (m *SubtractRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubtractRequest.Unmarshal(m, b)
}
func (m *SubtractRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubtractRequest.Marshal(b, m, deterministic)
}
func (m *SubtractRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubtractRequest.Merge(m, src)
}
func (m *SubtractRequest) XXX_Size() int {
	return xxx_messageInfo_SubtractRequest.Size(m)
}
func (m *SubtractRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubtractRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubtractRequest proto.InternalMessageInfo

func (m *SubtractRequest) GetCookie() int64 {
	if m != nil {
		return m.Cookie
	}
	return 0
}

func (m *SubtractRequest) GetValues() []int64 {
	if m != nil {
		return m.Values
	}
	return nil
}

type SubtractResponse struct {
	Result               int64    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubtractResponse) Reset()         { *m = SubtractResponse{} }
func (m *SubtractResponse) String() string { return proto.CompactTextString(m) }
func (*SubtractResponse) ProtoMessage()    {}
func (*SubtractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fc09a9db99872d4, []int{4}
}

func (m *SubtractResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubtractResponse.Unmarshal(m, b)
}
func (m *SubtractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubtractResponse.Marshal(b, m, deterministic)
}
func (m *SubtractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubtractResponse.Merge(m, src)
}
func (m *SubtractResponse) XXX_Size() int {
	return xxx_messageInfo_SubtractResponse.Size(m)
}
func (m *SubtractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubtractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubtractResponse proto.InternalMessageInfo

func (m *SubtractResponse) GetResult() int64 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*AddzConfig)(nil), "addz.AddzConfig")
	proto.RegisterType((*AddRequest)(nil), "addz.AddRequest")
	proto.RegisterType((*AddResponse)(nil), "addz.AddResponse")
	proto.RegisterType((*SubtractRequest)(nil), "addz.SubtractRequest")
	proto.RegisterType((*SubtractResponse)(nil), "addz.SubtractResponse")
}

func init() { proto.RegisterFile("addz/service.proto", fileDescriptor_7fc09a9db99872d4) }

var fileDescriptor_7fc09a9db99872d4 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xd1, 0x6a, 0xbb, 0x30,
	0x14, 0xc6, 0xff, 0xfd, 0x5b, 0xca, 0x38, 0x2d, 0xd4, 0x66, 0xac, 0x0c, 0xaf, 0x4a, 0x60, 0x30,
	0xc6, 0x88, 0x50, 0x2f, 0xd7, 0x1b, 0xbb, 0x37, 0xb0, 0x77, 0xbb, 0x29, 0x6a, 0x32, 0xe7, 0xe6,
	0x8c, 0x33, 0xb1, 0x88, 0x6f, 0xbc, 0xb7, 0x18, 0x49, 0x74, 0xba, 0x82, 0xbb, 0xd8, 0xe5, 0xf7,
	0xe5, 0xfb, 0x9d, 0x93, 0xc3, 0x39, 0x80, 0x42, 0x4a, 0x1b, 0x57, 0xb0, 0xf2, 0x94, 0xc6, 0x8c,
	0x14, 0x25, 0x97, 0x1c, 0x4d, 0x95, 0xe7, 0x5c, 0x6a, 0xe1, 0x86, 0x94, 0x96, 0x4c, 0x08, 0xf3,
	0x84, 0x3f, 0x27, 0x00, 0x3e, 0xa5, 0xcd, 0x23, 0xcf, 0x9f, 0xd3, 0x04, 0x79, 0xb0, 0x88, 0xd2,
	0x9c, 0x1e, 0xdb, 0xd0, 0xf5, 0x64, 0x33, 0xb9, 0x9d, 0x6f, 0x6d, 0xa2, 0xeb, 0xe5, 0x09, 0xf1,
	0x8d, 0x1f, 0xcc, 0x55, 0xaa, 0x15, 0x68, 0x07, 0xab, 0x57, 0xc1, 0xf3, 0xe3, 0x0f, 0xf2, 0xff,
	0x08, 0xb9, 0x54, 0xd1, 0xfd, 0x80, 0xf6, 0x60, 0x91, 0xf1, 0xa4, 0xf9, 0x06, 0xad, 0xb1, 0x96,
	0x2a, 0x35, 0x80, 0x58, 0x5d, 0xf4, 0xd0, 0x74, 0x0c, 0x52, 0xa9, 0x56, 0xe0, 0x9d, 0x1e, 0x35,
	0x60, 0x1f, 0x15, 0x13, 0x12, 0xad, 0x61, 0x16, 0x73, 0xfe, 0x96, 0x32, 0x3d, 0xa4, 0x15, 0xb4,
	0x4a, 0xf9, 0xa7, 0x30, 0xab, 0x98, 0x1a, 0xc1, 0x52, 0xbe, 0x51, 0xf8, 0x06, 0xe6, 0x9a, 0x16,
	0x05, 0xcf, 0x85, 0x8e, 0x95, 0x4c, 0x54, 0x99, 0xec, 0x70, 0xa3, 0xb0, 0x0f, 0xcb, 0x43, 0x15,
	0xc9, 0x32, 0x8c, 0xe5, 0x5f, 0x3b, 0xdd, 0x81, 0xdd, 0x97, 0xf8, 0xbd, 0xdd, 0xb6, 0xd6, 0xbf,
	0x6a, 0x0e, 0x66, 0xdf, 0xe8, 0x1e, 0x2c, 0x9f, 0x52, 0x64, 0x13, 0xb5, 0x71, 0xd2, 0x4f, 0xeb,
	0xac, 0x06, 0x8e, 0x29, 0x89, 0xff, 0xa1, 0x07, 0xb8, 0xe8, 0x1a, 0xa1, 0x2b, 0x13, 0x38, 0xfb,
	0xbb, 0xb3, 0x3e, 0xb7, 0x3b, 0x78, 0x8f, 0x9f, 0x36, 0x49, 0x2a, 0x5f, 0xaa, 0x88, 0xc4, 0xfc,
	0xdd, 0x65, 0x75, 0x91, 0x71, 0xca, 0x84, 0xdb, 0x6e, 0x40, 0x9d, 0x59, 0x13, 0xcd, 0xf4, 0x91,
	0x79, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x7a, 0xbc, 0xf8, 0x95, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AddzServiceClient is the client API for AddzService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddzServiceClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	Subtract(ctx context.Context, in *SubtractRequest, opts ...grpc.CallOption) (*SubtractResponse, error)
}

type addzServiceClient struct {
	cc *grpc.ClientConn
}

func NewAddzServiceClient(cc *grpc.ClientConn) AddzServiceClient {
	return &addzServiceClient{cc}
}

func (c *addzServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/addz.AddzService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addzServiceClient) Subtract(ctx context.Context, in *SubtractRequest, opts ...grpc.CallOption) (*SubtractResponse, error) {
	out := new(SubtractResponse)
	err := c.cc.Invoke(ctx, "/addz.AddzService/Subtract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddzServiceServer is the server API for AddzService service.
type AddzServiceServer interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
	Subtract(context.Context, *SubtractRequest) (*SubtractResponse, error)
}

func RegisterAddzServiceServer(s *grpc.Server, srv AddzServiceServer) {
	s.RegisterService(&_AddzService_serviceDesc, srv)
}

func _AddzService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddzServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/addz.AddzService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddzServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddzService_Subtract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubtractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddzServiceServer).Subtract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/addz.AddzService/Subtract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddzServiceServer).Subtract(ctx, req.(*SubtractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AddzService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "addz.AddzService",
	HandlerType: (*AddzServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _AddzService_Add_Handler,
		},
		{
			MethodName: "Subtract",
			Handler:    _AddzService_Subtract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "addz/service.proto",
}
